### PR TITLE
Bugfix/dashboard is blink

### LINKED ISSUE #2268: Dashboard console error when rendering proxy backend select widget
The dashboard on nightly.apinf.io is currently rendering blank. The following error is in the console:

```js
TypeError: Cannot read property 'name' of undefined
    at e.apiName (c984729….js?meteor_js_resource=true:447)
```

# Steps to reproduce
1. Log in as **admin** to nightly.apinf.io
2. Press Dashboard link

# Expected result
You are able to select an API for viewing

# Actual result
You see a blank page with only the title Dashboard

# Screenshot
empty dashboard

This may be due to a missing subscription in the Dashboard code:

screenshot_20170309_150406

### PR DESCRIPTION
**Pull request by marla-singer**
Closes #2268

### CODE REVIEW

**Comment by marla-singer** [comment]
@apinf/developers Ready for review

File: proxy_backends/collection/helpers.js [hunk 1]
```diff
@@ -1,19 +0,0 @@
...
-This file is covered by the EUPL license.
-You may obtain a copy of the licence at
-https://joinup.ec.europa.eu/community/eupl/og_page/european-union-public-licence-eupl-v11 */
-
-import Apis from '/apis/collection';
-import ProxyBackends from '/proxy_backends/collection';
-
-ProxyBackends.helpers({
-// eslint-disable-next-line object-shorthand
-  apiName: function () {
```
Comment (brylie) [inline proxy_backends/collection/helpers.js]: We want to be able to get the API Name dynamically at runtime. In general, we want to **avoid writing triggers that cause changes in multiple collections**.

There is probably a different solution in this space.

File: apis/client/profile/settings/details/autoform.js [hunk 2]
```diff
@@ -8,8 +8,27 @@ import { AutoForm } from 'meteor/aldeed:autoform';
...
+        const apiId = this.docId;
+        // Get related proxy backend configuration
+        const proxyBackend = ProxyBackends.findOne({ apiId });
+
+        // Make sure proxy backend configuration exists
+        if (proxyBackend) {
+          // Get the updated name
+          const apiName = this.updateDoc.$set.name;
+          // Update API name in proxy backend configuration
+          ProxyBackends.update(proxyBackend._id, { $set: { 'apiUmbrella.name': apiName } });
```
Comment (brylie) [inline apis/client/profile/settings/details/autoform.js]: Lets see if we can find a run-time solution here, rather than using an autoform **update** hook on the **API Details** form to mutate data in the **ProxyBackends** collection.

In general, we want to **avoid writing triggers that cause changes in multiple collections**.

File: proxy_backends/collection/helpers.js (hunk 1 above)
Comment (marla-singer) [inline proxy_backends/collection/helpers.js]: Ok. How do you assume to provide sorting in API selector?

File: apis/client/profile/settings/details/autoform.js (hunk 2 above)
Comment (marla-singer) [inline apis/client/profile/settings/details/autoform.js]: Don't see any reason to avoid trigger in this case.

**Comment by brylie** [comment]
I see that we have difficulties sorting data based on a collection helper. How does this relate to the internationalized sorting work done by @manzapanza? I.e. the select list should probably follow the same sorting rules as the API catalog (in terms of API name).

File: apis/client/profile/settings/details/autoform.js (hunk 2 above)
Comment (brylie) [inline apis/client/profile/settings/details/autoform.js]: Well, the collection helper was intended as a way to avoid the trigger. What are some options for sorting?

File: proxy_backends/collection/helpers.js (hunk 1 above)
Comment (brylie) [inline proxy_backends/collection/helpers.js]: I have asked @manzapanza to help us work through this challenge. Basically though, we are working with an array of objects, to create the select list. So, we might just map all of the proxy backends to retrieve the related API name and sort that based on localization rules.

File: dashboard/client/filtering/api_select/api_select.html [hunk 3]
```diff
@@ -12,7 +12,7 @@
     <optgroup label="{{_ 'apiSelectPicker_myApis' }}" >
       {{# each backend in proxyBackends }}
         <option value="{{ backend._id }}" >
-              {{ backend.apiName }}
+          {{ backend.apiUmbrella.name }}
```
Comment (brylie) [inline dashboard/client/filtering/api_select/api_select.html]: One additional thing to consider with this solution, is that we are actively working on multi-proxy support for our dashboard. So, the data structure `backend.apiUmbrella.name` is temporary. We can solve it this way for now, but this is another reason to consider alternative solutions.

File: proxy_backends/collection/helpers.js (hunk 1 above)
Comment (manzapanza) [inline proxy_backends/collection/helpers.js]: You could create a template helper to sort the collection on client side. Try something like this:

```
import 'locale-compare-polyfill';
...
proxyBackends.sort((a, b) => {
    return a.apiName.localeCompare(b.apiName, language);
});
```

**Comment by marla-singer** [comment]
@brylie Ready for review
