### PR TITLE
If API has API Umbrella proxy, return proxy URL instead of API URL in API data

### LINKED ISSUE #3016: Proxy URLs not shown in Catalog API
**Title**: 

Proxy URLs not shown in Catalog API

**Steps to Reproduce**: 
1. Create a new API providing the backend URL

captura de pantalla 2017-10-05 a las 11 19 37

2. Configure the proxy for securing the API

captura de pantalla 2017-10-05 a las 11 20 25

captura de pantalla 2017-10-05 a las 11 20 35

3. Make a GET request to /rest/v1/apis to retrieve API Information

captura de pantalla 2017-10-05 a las 11 19 49
                    
**Outcome**:

The URL field included in the API resource of the Apinf REST API is always the backend URL used for creating the API, so when a proxy has been configured the API URL displayed in the portal and the one given by the catalog API are different.
         
**Expected Behavior**:

The URL field of the APIs resource should correspond to the API URL displayed in Apinf portal, which is the URL that should be used in order to access to the service
                   
**Environment**:

Apinf Docker image, develop tag

### PR DESCRIPTION
**Pull request by matleppa**
Closes #3016

## Changes
Describe your changes here as a bulleted list:
- method /GET/apis
  - replace API URL with proxy URL in returned API data, if API is connected to API Umbrella proxy
- method /GET/apis/\<API id\>
  - replace API URL with proxy URL in returned API data, if API is connected to API Umbrella proxy

## Developer checklist
This checklist is to be completed by the PR developer:

- [ ] Alternative solutions were compared/discussed before writing code
    - [ ] trade-offs with this solution are considered acceptable
- [x] Code in this PR adheres to the [project styleguide](CONTRIBUTING.md)
- [x] This pull request does not decrease project test coverage
- [ ] If the code changes existing database collection(s), migration has been written
- [ ] If UI texts are added or changed, all texts are internationalized

## Reviewer checklist
Reviewed by: @username1

This list is to be completed by the pull request reviewer:
- [ ] Code works as described/expected
- [ ] Code seems to be error free
    - [ ] no browser console errors visible
    - [ ] no server console errors visible
    - [ ] passes CI build
- [ ] Code is written in a way that promotes maintainability
    - [ ] easy to understand
    - [ ] well organized
    - [ ] follows project coding standards and conventions
    - [ ] well documented

### CODE REVIEW

File: apinf_packages/apis/server/api.js [hunk 1]
```diff
@@ -14,6 +14,7 @@ import Apis from '/apinf_packages/apis/collection';
 import CatalogV1 from '/apinf_packages/rest_apis/server/catalog';
 import Organizations from '/apinf_packages/organizations/collection';
 import Authentication from '/apinf_packages/rest_apis/server/authentication';
```
Comment (marla-singer) [inline apinf_packages/apis/server/api.js]: Please move all imports for `/apinf_packages/rest_apis/..` from "Collection imports" to "APInf import" part

**Comment by marla-singer** [comment]
@matleppa Can you please squash all your commits into one?
1. 
> git rebase develop -i
2. 
> pick cdd88c4 If API has proxy, return proxy URL instead of API URL in API data
s 92774aa Moved REST API related imports under APInf imports section
s ef08377 Eslint max-length disabled only for one row instead of entire file
s 77390f3 Fixed too long lines

3. 
> # This is a combination of 4 commits.
# The first commit's message is:
If API has proxy, return proxy URL instead of API URL in API data

- Moved REST API related imports under APInf imports section
# Please enter the commit message for your changes. Lines starting

4. After success result `git push -f`
