### PR TITLE
fixed issue Feedback issues should be threads #2265

### LINKED ISSUE #2265: Feedback issues should be threads
## Current look and feel
screenshot at maaliskuuta 08 22-07-09

## Need
As API owner I have no opportunity to respond to feedback. In addition I would love to see that feedback list behave like a threaded discussion so that there can be back-traced discussions, not just notes. This came to my mind when I was thinking to ask my developer network to give feedback about the API design by putting feedback with our tools in the feedback tab. I really would like to respond and discuss the item there, not just remove it. Responding would be engaging.

# Goal 
added by @bajiat 2017-10-06

* [ ] Any registered user 
  * [ ] can reply to a public feedback item
  * [ ] can reply to a reply item
* [ ] The username of the person giving feedback or replying to feedback is displayed along with the feedback
* [ ] If a user is replying to an existing feedback item or another reply
  * [ ] There is a UI text indicating who the user is replying to
  * [ ] The replies to an original feedback item are displayed indented
* [ ] API owner and admin can 
  * [ ] make all feedback private
  * [ ] make an individual feedback private
  * [ ] delete a feedback item
* [ ]  Any registered user can upvote or downvote an individual feedback item

## Mockups
Archive includes desktop and mobile views.
[feedback.zip](https://github.com/apinf/platform/files/1362287/feedback.zip)

Here you can see basic prototype:
https://invis.io/SYDU0V94C

### PR DESCRIPTION
**Pull request by saransh-dev**
# Closes #2265 

## Changes
- Changed api feedback UI
- Allow user to comment on feedback

## Developer checklist
This checklist is to be completed by the PR developer:

- [x] Alternative solutions were compared/discussed before writing code
- [x] trade-offs with this solution are considered acceptable
- [x] Code in this PR adheres to the [project styleguide](CONTRIBUTING.md)
- [x] This pull request does not decrease project test coverage
- [x] If the code changes existing database collection(s), migration has been written
- [x] If UI texts are added or changed, all texts are internationalized

## Reviewer checklist
Reviewed by: @marla-singer @55 

This list is to be completed by the pull request reviewer:
- [x] Code works as described/expected
- [x] Code seems to be error free
    - [x] no browser console errors visible
    - [x] no server console errors visible
    - [x] passes CI build
- [x] Code is written in a way that promotes maintainability
    - [x] easy to understand
    - [x] well organized
    - [x] follows project coding standards and conventions
    - [x] well documented

### CODE REVIEW

**Comment by marla-singer** [comment]
@saransh-dev Take it on review

**Comment by 55** [comment]
I will leave my comments once @marla-singer is done with her review.

**Comment by marla-singer** [comment]
@55 I'm reviewing code style and how it works. Please review how it looks. Because I have a couple remarks about that

**Comment by 55** [comment]
@marla-singer @saransh-dev sorry for the lack of the description for the provided mockups.
I will add a more prominent description with comments to the already implemented UI during today.

**Comment by marla-singer** [comment]
_Copied from related issue:_
@55 @Nazarah 
I have a lot of questions about these part

1. What about edit/delete Reply?

> make all feedback private

2. What about "make all feedbacks public"? The early implementation has logic for that
joxi_screenshot_1507710205636

3. The reply of reply must be as nested element. Because it isn't obviously that it is a reply of reply and what is the parent of current reply.

Look at the screen below. The numbers mean the order I added the items. 
joxi_screenshot_1507710274902

4. As for me the lock icon needs a help text like "Make all feedbacks private" because it isn't obviously

5. Also I don't like that we have an additional step for control visibility as Modal form. Does it really need?
joxi_screenshot_1507710687014

6. 
>  API owner and admin can
 make all feedback private
 make an individual feedback private
 delete a feedback item

What about feedback author permissions? The early implementation has logic for that
joxi_screenshot_1507711364022

**Comment by 55** [comment]
@marla-singer @saransh-dev sorry for the lack of the description for the provided mockups. I will try to provide more understandable and easy to use instructions for the upcoming tasks.
I will add a more prominent description with comments to the already implemented UI during today.

**Comment by marla-singer** [comment]
@saransh-dev Anonym user has access to Reply button
joxi_screenshot_1507711225779 1

**Comment by saransh-dev** [comment]
> @saransh-dev Anonym user has access to Reply button

@marla-singer I will take care this

File: apinf_packages/entityComment/collection/permissions.js [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+    // Only allow logged in user to comment
+    if (userId) {
+      return true;
+    }
+    return false;
+  },
+  update (userId, entityComment) {
+    // only allow user to update own comment
+    if (userId && entityComment && entityComment.authorId &&
+      userId === entityComment.authorId) {
```
Comment (marla-singer) [inline apinf_packages/entityComment/collection/permissions.js]: 1. You use entity.authorId twice so store it in variable like
```js
const authorId = entityComment && entityComment.authorId
```
It means authorId will store value of `entityComment.authorId` if entityComment exists otherwise will store undefined

2. Use the shorter version
```js
// Make sure user is logged and author of current entity
return !!(userId && userId === authorId)
```

File: apinf_packages/entityComment/collection/permissions.js [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+      return true;
+    }
+    return false;
+  },
+  remove (userId, entityComment) {
+    if (entityComment) {
+      /* 1. Allow user to remove own comment */
+      if (userId && entityComment.authorId &&
+        userId === entityComment.authorId) {
+        return true;
```
Comment (marla-singer) [inline apinf_packages/entityComment/collection/permissions.js]: The same stuff is here

1. Variable to store ` entityComment.authorId`
2. The simplify condition as `userId && userId === authorId`

File: apinf_packages/entityComment/collection/permissions.js [hunk 3]
```diff
@@ -0,0 +1,56 @@
...
+      }
+      let api = {};
```
Comment (marla-singer) [inline apinf_packages/entityComment/collection/permissions.js]: Move comment `/* 2. Allow admins & API owners/managers remove comments */` to here and add an empty line

File: apinf_packages/entityComment/collection/permissions.js [hunk 4]
```diff
@@ -0,0 +1,56 @@
...
+      switch (entityComment.type) {
```
Comment (marla-singer) [inline apinf_packages/entityComment/collection/permissions.js]: Add an empty line

File: apinf_packages/entityComment/collection/permissions.js [hunk 5]
```diff
@@ -0,0 +1,56 @@
...
+        case 'Feedback': {
+          /* 2. Allow admins & API owners/managers remove comments */
```
Comment (marla-singer) [inline apinf_packages/entityComment/collection/permissions.js]: Remove this comment from here

File: apinf_packages/entityComment/collection/permissions.js (hunk 3 above)
Comment (marla-singer) [reply apinf_packages/entityComment/collection/permissions.js]: And don't specify `{}`. The empty object returns true and the expression `api && api.currentUserCanManaga()` will return undefined.
Just leave `let api;` The default value is undefined

File: apinf_packages/entityComment/collection/permissions.js [hunk 6]
```diff
@@ -0,0 +1,56 @@
...
+          // Get feedback by feedbackId of the feedback comment
+          const feedback = Feedback.findOne(entityComment.postId);
+          if (feedback) {
```
Comment (marla-singer) [inline apinf_packages/entityComment/collection/permissions.js]: Add the empty line above

File: apinf_packages/feedback/client/comment/form/autoform.js [hunk 7]
```diff
@@ -0,0 +1,39 @@
...
+import feedbackData from '../../item/item.js';
+
+AutoForm.hooks({
+  commentForm: {
+    before: {
+      insert (comment) {
+        const feedback = feedbackData.get();
+        comment.postId = feedback.postId;
+        comment.type = feedback.type;
+        comment.commentedOn = feedback.commentedOn ? feedback.commentedOn : '';
```
Comment (marla-singer) [inline apinf_packages/feedback/client/comment/form/autoform.js]: THe shorter version is `comment.commentedOn =  feedback.commentedOn || '';`

File: apinf_packages/feedback/client/comment/item/item.html [hunk 8]
```diff
@@ -0,0 +1,31 @@
...
+      </div>
+      
+      <div class="feedback-message">
+        <p>
+          {{ item.comment }}
+        </p>
+      </div>
+      <div class="reply-to-feedback-reply">
+        <button id="{{item._id}}" class="pull-left comment-reply">
+          Reply
```
Comment (marla-singer) [inline apinf_packages/feedback/client/comment/item/item.html]: i18n tag

File: apinf_packages/feedback/client/feedback.less [hunk 9]
```diff
@@ -3,10 +3,22 @@ This file is covered by the EUPL license.
 You may obtain a copy of the licence at
 https://joinup.ec.europa.eu/community/eupl/og_page/european-union-public-licence-eupl-v11 */
 
-#feedback-visibility-options {
-  margin-right: 1em;
+
+#feedback-title {
+	display: inline-block;
```
Comment (marla-singer) [inline apinf_packages/feedback/client/feedback.less]: Fix all indent in this file. We have 2 space bars

File: apinf_packages/feedback/client/item/item.html [hunk 10]
```diff
@@ -5,74 +5,88 @@
...
-        <b>
-          {{ item.author }}
-        </b>
-        <i>
-          {{ relativeTimeStamp item.createdAt }}
-        </i>
+      <div class="row">
+        <div class="col-md-10">
+          <button id="{{item._id}}" class="pull-left feedback-reply">
+            Reply
```
Comment (marla-singer) [inline apinf_packages/feedback/client/item/item.html]: i81n tag

File: apinf_packages/feedback/client/item/item.js [hunk 11]
```diff
@@ -18,15 +19,26 @@ import moment from 'moment';
...
 
+const feedbackData = new ReactiveVar(false);
+
 Template.feedbackItem.onCreated(function () {
   // Get ID of current feedback object
   const feedbackId = Template.currentData().item._id;
 
   // Subscribe to votes for this feedback
   this.subscribe('getAllVotesForSingleFeedback', feedbackId);
+  // this.subscribe('getCommentForSingleFeedback', feedbackId);
```
Comment (marla-singer) [inline apinf_packages/feedback/client/item/item.js]: Remove comment

File: apinf_packages/feedback/client/item/item.js [hunk 12]
```diff
@@ -18,15 +19,26 @@ import moment from 'moment';
 // Collection imports
 import FeedbackVotes from '/apinf_packages/feedback_votes/collection';
 
+const feedbackData = new ReactiveVar(false);
```
Comment (marla-singer) [inline apinf_packages/feedback/client/item/item.js]: Hm. Bad solution. You mix Template declaration with imported value. It must be resolved another way

File: apinf_packages/feedback/collection/server/publications.js [hunk 13]
```diff
@@ -9,6 +9,7 @@ import { check } from 'meteor/check';
 
 // Collection imports
 import FeedbackVotes from '/apinf_packages/feedback_votes/collection';
+import EntityComment from '/apinf_packages/entityComment/collection';
```
Comment (marla-singer) [inline apinf_packages/feedback/collection/server/publications.js]: Save the alphabetical order

**Comment by marla-singer** [comment]
I prepared the first part of requested changes. After time I will review again

File: apinf_packages/entityComment/collection/permissions.js (hunk 1 above)
Comment (saransh-dev) [reply apinf_packages/entityComment/collection/permissions.js]: > Use the shorter version
>
> // Make sure user is logged and author of current entity
> return !!(userId && userId === authorId)

I need to use following code instead of above:-
```
if (userId && userId === authorId) {
        return true;
}
```

Because above one also return `false`, but i don't want to return `false` :- 
```
      const authorId = entityComment && entityComment.authorId
      if (userId && userId === authorId) {
        return true;
      }
      let api = {};
      switch (entityComment.type) {
        case 'Feedback': {
          /* 2. Allow admins & API owners/managers remove comments */
          // Get feedback by feedbackId of the feedback comment
          const feedback = Feedback.findOne(entityComment.postId);
          if (feedback) {
            // Get api by feedback apiBackendId
            api = Apis.findOne(feedback.apiBackendId);
          }
          break;
        }
        default: {
          break;
        }
      }
```

File: apinf_packages/entityComment/collection/permissions.js (hunk 2 above)
Comment (saransh-dev) [reply apinf_packages/entityComment/collection/permissions.js]: > The same stuff is here
>
>    Variable to store entityComment.authorId
>    The simplify condition as userId && userId === authorId


I need to use following code instead of above:-
```
if (userId && userId === authorId) {
        return true;
}
```

Because above one also return `false`, but i don't want to return `false` at this postion :- 
```
     if (entityComment) {
      /* 1. Allow user to remove own comment */
      const authorId = entityComment && entityComment.authorId
      if (userId && userId === authorId) {
        return true;
      }
      let api = {};
      switch (entityComment.type) {
        case 'Feedback': {
          /* 2. Allow admins & API owners/managers remove comments */
          // Get feedback by feedbackId of the feedback comment
          const feedback = Feedback.findOne(entityComment.postId);
          if (feedback) {
            // Get api by feedback apiBackendId
            api = Apis.findOne(feedback.apiBackendId);
          }
          break;
        }
        default: {
          break;
        }
      }
      // Return true/false based on edit permissions of api
      return (api && api.currentUserCanManage());
    }
    // Otherwise deny remove comment
    return false;
```

File: apinf_packages/entityComment/collection/permissions.js (hunk 3 above)
Comment (saransh-dev) [reply apinf_packages/entityComment/collection/permissions.js]: @marla-singer Can Admin or api owner can edit or delete comment ? Please advise

**Comment by 55** [comment]
@marla-singer @saransh-dev 

feedback-own-reply-with-comments

1. Edit/delete/make private actions fore feedback are available in dropdown menu (three dotes icon). For reply I added edit and delete.

2. Lock icon now instead of two buttons we had before. When you click it changes color and makes all feddback private/public.

3. Instead of nested elements we are using names of a user you are replying to.

4. Yes, I agree, it needs a help text like "Make all feedbacks private" on hover. Maybe for the first time it's not that obvious, but after user learns, it will be less annoying compare to the seeing "Make private" text as we have now,

5. Yes, let's remove this confirmation.

6. We should have the same permissions with the addition: only author of the feedback or reply can edit it.


@saransh-dev 
Here is a first part of additional changes:

- [ ] when user clicks(hovers) on up vote color and rectangular color should change to `#cceea7` for positive, and `#eda6a6` for negative

- [ ] instead of `reply` link under own reply there should be `edit` (when clicked same form as for adding reply appears) and `delete` buttons

- [ ] when hover and clicked on lock icon to make all feedbacks private color changes to `#333` and back to `#9b9b9b` when to make public

- [ ] remove confirmation dialog when making feedbacks private/public

- [ ] changes font sizes according the picture I attached

- [ ] make sure that only author of the feedback or reply can edit it

File: apinf_packages/entityComment/collection/permissions.js (hunk 2 above)
Comment (marla-singer) [reply apinf_packages/entityComment/collection/permissions.js]: @saransh-dev I got you don't need to return false and because of that I wrote: "The simplify condition" :) No words about return :ok_hand: 

Anyway, you've got my idea
```js
const authorId = entityComment && entityComment.authorId
      if (userId && userId === authorId) {
        return true;
      }
```

File: apinf_packages/entityComment/collection/permissions.js (hunk 3 above)
Comment (marla-singer) [reply apinf_packages/entityComment/collection/permissions.js]: @saransh-dev Admin and API owner/maanger can edit and delete comment.
I meant why you don't need to use `{}` as default value in this case.

The sum up:
1. Move comment /* 2. Allow admins & API owners/managers remove comments */ to here and add an empty line as separation
2. Declare `api` variable as `let api;`

Comment (saransh-dev) [reply apinf_packages/entityComment/collection/permissions.js]: @marla-singer But on UI, there is edit & delete options for only Feedback, not for comment.

Comment (saransh-dev) [reply apinf_packages/entityComment/collection/permissions.js]: @marla-singer Can reply owner can also edit or delete own reply ? Please advise.

**Comment by saransh-dev** [comment]
@55 As @marla-singer  suggested, Admin and owner/manger can also update/delete comment.

>  marla-singer 14 hours ago Member
>
>@saransh-dev Admin and API owner/maanger can edit and delete comment.

**Comment by marla-singer** [comment]
> I have an idea, Admin and Owner/Manager of feedback can able to reply or delete any comment but not edit

@saransh-dev Let's go with it

**Comment by Nazarah** [comment]
>Yes, I agree, it needs a help text like "Make all feedbacks private" on hover. Maybe for the first time it's not that obvious, but after user learns, it will be less annoying compare to the seeing "Make private" text as we have now,

>Yes, let's remove this confirmation.

@marla-singer @55 @saransh-dev  if you wish to remove the confirmation, make sure on making all feedback private/public, there is an s-alert giving feedback about this action. User should be aware of the taken action and that doesn't get achieved only with button click action.

**Comment by 55** [comment]
@Nazarah I would keep it as enhancement if needed. User get's enough of visual feedbacks (like color change, icons and color). Let first @saransh-dev finish current to-do list.

**Comment by saransh-dev** [comment]
>3. The reply of reply must be as nested element. Because it isn't obviously that it is a reply of reply and what is the parent of current reply.

@marla-singer We can identify that whose reply is this like below:- 

Reply

**Comment by 55** [comment]
@saransh-dev yes, I thought about it, good idea. 
But I would really suggest first to complete already requested changes.

**Comment by Nazarah** [comment]
>I would keep it as enhancement if needed. User gets enough of visual feedbacks (like color change, icons and color). Let first @saransh-dev finish current to-do list.

Lets close the PR with @saransh-dev 's work.
But I strongly emphasize about having an s-alert in case major confirmation windows are removed.
True there are elements that would change color/state on performing an action.
However, in the UI they are small in size
Think about seeing them on a large screen or mobile screen, where the elements would be placed along with other contents.
So at the first glance on making an action, it might take some while for the users find out and understand what has happened for that action.
In the long run expert users would learn about the feature, but for the very first time users, it is needed.
And S-alerts simple and they go away on their own, so that shouldn't make to much impact on the UI and color contrasts.
I am opening an enhancement issue about this.

**Comment by saransh-dev** [comment]
Hi @marla-singer, 
I have a confusion that i want to use single code of autoform for insert and update as well but when i click on first reply, it opens edit form but show last reply message.

Please advise how i can resolve this.

**Comment by marla-singer** [comment]
@saransh-dev Check Autoform docs -- https://github.com/aldeed/meteor-autoform

**Comment by saransh-dev** [comment]
@marla-singer how we can identify that all feedback are either `private` or `public` ?
We can use a variable in `feebackIsPublic` in related api. If it is true then all feedback display if not then do not display. But in case of not, we can also hide send feedback button (becase if user submit new feedback it will not display due to `false` value of `feebackIsPublic`). For this issue we can hide submit button also and show a message like that *feedback is private*.

Please advise

**Comment by marla-singer** [comment]
> how we can identify that all feedback are either private or public ?

What does impede you to take all feedbacks of current API and check each item? After that save result in the template variable

**Comment by saransh-dev** [comment]
Hi @marla-singer,

I have one cinfusion:-
 
Here are `EntityComment` records:-
```
{
	"_id" : "NXKBekSgHjDDfCFMC",
	"comment" : "1st comment",
	"postId" : "erE4ZSckFbaAhr4jv",
	"type" : "Feedback",
	"authorId" : "FJ29ry3wGAqKZFwDh",
	"createdAt" : ISODate("2017-10-20T12:10:30.444Z"),
	"commentedOn" : "NXKBekSgHjDDfCFMC",
	"updated_at" : ISODate("2017-10-23T11:37:36.416Z")
}
{
	"_id" : "97JqQZaQHkWnhDLJC",
	"postId" : "5gc3S9MaqB4mniLm7",
	"type" : "Feedback",
	"comment" : "2nd comment",
	"authorId" : "FJ29ry3wGAqKZFwDh",
	"createdAt" : ISODate("2017-10-20T17:31:32.922Z")
}

{
	"_id" : "aPtnsnAKMavWcSxXf",
	"postId" : "erE4ZSckFbaAhr4jv",
	"type" : "1.1 comment",
	"commentedOn" : "NXKBekSgHjDDfCFMC",
	"comment" : "ddddd",
	"authorId" : "nLCGzxZa74fMgqdtd",
	"createdAt" : ISODate("2017-10-20T18:03:31.869Z")
}
{
	"_id" : "apvpqxSeQ98WYYNY2",
	"postId" : "erE4ZSckFbaAhr4jv",
	"type" : "Feedback",
	"commentedOn" : "97JqQZaQHkWnhDLJC",
	"comment" : "2.1 comment",
	"authorId" : "FJ29ry3wGAqKZFwDh",
	"createdAt" : ISODate("2017-10-20T18:04:22.893Z")
}
{
	"_id" : "aPtnsnAKMavWcSxXf",
	"postId" : "erE4ZSckFbaAhr4jv",
	"type" : "Feedback",
	"commentedOn" : "aPtnsnAKMavWcSxXf",
	"comment" : "1.1.1 comment",
	"authorId" : "FJ29ry3wGAqKZFwDh",
	"createdAt" : ISODate("2017-10-21T06:10:07.786Z")
}
{
	"_id" : "dB996c8ZTmPrmea2o",
	"postId" : "erE4ZSckFbaAhr4jv",
	"type" : "Feedback",
	"commentedOn" : "aPtnsnAKMavWcSxXf",
	"comment" : "1.1.1.1 comment",
	"authorId" : "FJ29ry3wGAqKZFwDh",
	"createdAt" : ISODate("2017-10-23T06:42:35.305Z")
}
{
	"_id" : "aPtnsnAKMavWcSxXf",
	"postId" : "erE4ZSckFbaAhr4jv",
	"type" : "Feedback",
	"commentedOn" : "apvpqxSeQ98WYYNY2",
	"comment" : "2.1.1 comment",
	"authorId" : "nLCGzxZa74fMgqdtd",
	"createdAt" : ISODate("2017-10-20T18:03:31.869Z")
}
{
	"_id" : "apvpqxSeQ98WYYNY2",
	"postId" : "erE4ZSckFbaAhr4jv",
	"type" : "Feedback",
	"commentedOn" : "aPtnsnAKMavWcSxXf",
	"comment" : "2.1.1.1 comment",
	"authorId" : "FJ29ry3wGAqKZFwDh",
	"createdAt" : ISODate("2017-10-20T18:04:22.893Z")
}
```


Here is flow of above record using `_id` :-

```
|-	NXKBekSgHjDDfCFMC => 1st comment
	|-	aPtnsnAKMavWcSxXf => 1.1 comment
		|-	aPtnsnAKMavWcSxXf => 1.1.1 comment
			|-	dB996c8ZTmPrmea2o => 1.1.1.1 comment

|-	NXKBekSgHjDDfCFMC => 2nd comment
	|-	aPtnsnAKMavWcSxXf => 2.1 comment
		|-	aPtnsnAKMavWcSxXf => 2.1.1 comment
			|-	dB996c8ZTmPrmea2o => 2.1.1.1 comment
```


Like above example, we have `n-th` level reply of reply. When we delete parent reply then all child should be delete. So I am facing problem to get all reply of reply till `n-th` level.

I have an solution but I am not sure its good or not. We can set only one level or reply like below:-

```
|-	NXKBekSgHjDDfCFMC => 1st comment
|-	aPtnsnAKMavWcSxXf => 1.1 comment
|-	aPtnsnAKMavWcSxXf => 1.1.1 comment
|-	dB996c8ZTmPrmea2o => 1.1.1.1 comment

|-	NXKBekSgHjDDfCFMC => 2nd comment
|-	aPtnsnAKMavWcSxXf => 2.1 comment
|-	aPtnsnAKMavWcSxXf => 2.1.1 comment
|-	dB996c8ZTmPrmea2o => 2.1.1.1 comment
```

Please advise.

**Comment by saransh-dev** [comment]
And we can add like facebook in 2 level:-

```
|-	NXKBekSgHjDDfCFMC => 1st comment
	|-	aPtnsnAKMavWcSxXf => 1.1 comment
	|-	aPtnsnAKMavWcSxXf => 1.1.1 comment
	|-	dB996c8ZTmPrmea2o => 1.1.1.1 comment

|-	NXKBekSgHjDDfCFMC => 2nd comment
	|-	aPtnsnAKMavWcSxXf => 2.1 comment
	|-	aPtnsnAKMavWcSxXf => 2.1.1 comment
	|-	dB996c8ZTmPrmea2o => 2.1.1.1 comment
```
It also easy to delete.

**Comment by saransh-dev** [comment]
Hi @all, I am working on `edit comment`. So edit functionality on comment is not working yet.

**Comment by saransh-dev** [comment]
Hi @marla-singer,

I am trying to edit comment but I am not getting result.

```
{{# autoForm
  id="commentForm"
  collection=entityCommentCollection
  type=commentFormType
  doc=currnetDoc
}}
```

`commentFormType` having either `insert` or `update` and `currnetDoc` having current comment data only of `commentFormType` is `update`.

When I edit first comment in thread it updated correctly but when I click on comment edit button, it opens form and show correct value of that form but after submit, it updates first comment in the thread.
Please check below GIF:-

edit-comment


Please advise.

File: apinf_packages/entityComment/collection/schema.js [hunk 14]
```diff
@@ -0,0 +1,79 @@
...
+  },
+  comment: {
+    type: String,
+    max: 1000,
+    optional: false,
+    autoform: {
+      rows: 5,
+    },
+  },
+  commentedOn: {
```
Comment (marla-singer) [inline apinf_packages/entityComment/collection/schema.js]: What does this filed need? What will it store?

**Comment by marla-singer** [comment]
@saransh-dev I am in process of fixing troubles with Edit comment

**Comment by saransh-dev** [comment]
Hi, `commentedOn` is used to store parent comment's `_id` that the user going to reply. And find the author name of parent comment through this comment's `_id`.

**Comment by marla-singer** [comment]
@saransh-dev It is not a trivial issue to Edit reply so I believe we can move it as the next step.

I prepared PR where I cleaned up a code with "Edit" functional & made some changes. Please check it and if everything is okay - merge 
PR #3083

File: apinf_packages/apis/collection/schema.js [hunk 15]
```diff
@@ -134,6 +134,11 @@ Apis.schema = new SimpleSchema({
     optional: true,
     defaultValue: true,
   },
+  feedbackIsPublic: {
```
Comment (marla-singer) [inline apinf_packages/apis/collection/schema.js]: Remove this field from schema

File: apinf_packages/feedback/client/comment/comment.less [hunk 16]
```diff
@@ -0,0 +1,10 @@
+/* Copyright 2017 Apinf Oy
+This file is covered by the EUPL license.
+You may obtain a copy of the licence at
+https://joinup.ec.europa.eu/community/eupl/og_page/european-union-public-licence-eupl-v11 */
+
+
+.feedback-comment-list {
+	margin-left: 3em;
```
Comment (marla-singer) [inline apinf_packages/feedback/client/comment/comment.less]: Change indent to 2 spacebars (not 4) and add a new line in the end of the file

File: apinf_packages/feedback/client/comment/form/form.js [hunk 17]
```diff
@@ -0,0 +1,70 @@
...
+        break;
+      }
+    }
+
+    return comment;
+  },
+});
+
+
+Template.commentForm.events({
```
Comment (marla-singer) [inline apinf_packages/feedback/client/comment/form/form.js]: Remove one an empty line

File: apinf_packages/feedback/client/comment/list/list.js [hunk 18]
```diff
@@ -0,0 +1,28 @@
...
+
+Template.feedbackCommentList.onCreated(function () {
+  // Subscribe to comments for this feedback
+  this.subscribe('getCommentForSingleFeedback', this.data.feedback._id);
+});
+
+Template.feedbackCommentList.helpers({
+  userFeedbackComment () {
+		// Return Comments for this feedback
+    return EntityComment.find({
```
Comment (marla-singer) [inline apinf_packages/feedback/client/comment/list/list.js]: Fix indent of the comment

File: apinf_packages/feedback/client/feedback.less (hunk 9 above)
Comment (marla-singer) [reply apinf_packages/feedback/client/feedback.less]: Change indent to 2 spacebars (not 8) in the whole file

File: apinf_packages/apis/collection/schema.js (hunk 15 above)
Comment (saransh-dev) [reply apinf_packages/apis/collection/schema.js]: Done

File: apinf_packages/feedback/client/comment/comment.less (hunk 16 above)
Comment (saransh-dev) [reply apinf_packages/feedback/client/comment/comment.less]: Done

File: apinf_packages/feedback/client/comment/form/form.js (hunk 17 above)
Comment (saransh-dev) [reply apinf_packages/feedback/client/comment/form/form.js]: Done

File: apinf_packages/feedback/client/comment/list/list.js (hunk 18 above)
Comment (saransh-dev) [reply apinf_packages/feedback/client/comment/list/list.js]: Done

**Comment by marla-singer** [comment]
@55 No remarks from my side
