### PR TITLE
Fix REST API: Make sure a new organization name is unique

### LINKED ISSUE #3372: REST API: New organization name must be unique
### Problem
Endpoint POST /organizations

When a new Organization is created, it is not checked, if the name is already in use, thus an uncontrolled error message is generated.

Within PR 3140 (Bugfix/api view not loading 特殊天) the Organization names changed to be unique, but this requirement is not implemented to Management API.

### Solution
When an Organization is created with Management API, add checking of Organization name uniqueness.

### PR DESCRIPTION
**Pull request by matleppa**
Closes #3372 

## Changes

- POST /organizations
  - check that given name is unique
 
- PUT /organisations
  - check that given name is unique

## Developer checklist
This checklist is to be completed by the PR developer:

- [ ] Alternative solutions were compared/discussed before writing code
    - [ ] trade-offs with this solution are considered acceptable
- [ ] Code in this PR adheres to the [project styleguide](CONTRIBUTING.md)
- [ ] This pull request does not decrease project test coverage
- [ ] If the code changes existing database collection(s), migration has been written
- [ ] If UI texts are added or changed, all texts are internationalized

## Reviewer checklist
Reviewed by: @username1

This list is to be completed by the pull request reviewer:
- [ ] Code works as described/expected
- [ ] Code seems to be error free
    - [ ] no browser console errors visible
    - [ ] no server console errors visible
    - [ ] passes CI build
- [ ] Code is written in a way that promotes maintainability
    - [ ] easy to understand
    - [ ] well organized
    - [ ] follows project coding standards and conventions
    - [ ] well documented

### CODE REVIEW

File: apinf_packages/organizations/server/api.js [hunk 1]
```diff
@@ -504,8 +526,17 @@ ManagementV1.addRoute('organizations/:id', {
         if (!isValid) {
           return errorMessagePayload(400, 'Parameter "name" is erroneous or missing');
         }
+        // Organization with same name must not already exist
+        const duplicateOrganization = Organizations.findOne({ name: bodyParams.name });
+
+        if (duplicateOrganization) {
+          const detailLine = 'Duplicate: Organization with same name exists.';
```
Comment (marla-singer) [inline apinf_packages/organizations/server/api.js]: Can we simplify this text? 
```js
const message = `Organization with same name exists and has id ${duplicateOrganization._id}`
return errorMessagePayload(400, message)
```

File: apinf_packages/organizations/server/api.js [hunk 2]
```diff
@@ -319,9 +328,22 @@ ManagementV1.addRoute('organizations', {
 
       // If insert failed, stop and send response
       if (!organizationId) {
-        return errorMessagePayload(500, 'Insert organization failed. Organization not created');
+        return errorMessagePayload(500, 'Insert organization failed. Organization not created!');
       }
 
+      // Add slug to Organization
```
Comment (marla-singer) [inline apinf_packages/organizations/server/api.js]: It relates to another issue. The taken issue is about Uniqueness organization name, not about create slug. 
If you want to fix it as well in the current PR then assign yourself at the issue

Comment (matleppa) [reply apinf_packages/organizations/server/api.js]: Yes, this can be done only after issue 3389 is implemented.

File: apinf_packages/organizations/server/api.js (hunk 1 above)
Comment (matleppa) [reply apinf_packages/organizations/server/api.js]: This is same functionality as in API name uniqueness check. In case there already is one with same name, return the id of it as a separate parameter.
