### PR TITLE
Bugfix/api view not loading 特殊天

### LINKED ISSUE #3101: API view not loading - 特殊天
**Steps to Reproduce**: 
1. go to page: https://apinf.io
2. Scroll down to "Latest APIs"
3. click topic of mysterious "Special day" API (screenshot below)
screenshot at marraskuuta 06 20-10-29
                    
**Outcome**:

On click, page goes to https://apinf.io/apis (the link in API card is also to https://apinf.io/apis)

**Expected Behavior**:

- Use proper link to API profile page in API card view
- Open selected API profile detailed view. 
                   
**Environment**:

Mac, FF (56.0.2), APInf production site (https://apinf.io)

### PR DESCRIPTION
**Pull request by deligence-dharmendra**
Closes #3101

## Changes

- add new node package 'limax'
- chnages in api autoform js
- remove file slugs.js for api name
- remove organization slugs.js
- add new api slug migration
- add new organization slug migration
- add new migration for manage duplicate organization name

## Developer checklist
This checklist is to be completed by the PR developer:

- [ ] Alternative solutions were compared/discussed before writing code
    - [ ] trade-offs with this solution are considered acceptable
- [ ] Code in this PR adheres to the [project styleguide](CONTRIBUTING.md)
- [ ] This pull request does not decrease project test coverage
- [ ] If the code changes existing database collection(s), migration has been written
- [ ] If UI texts are added or changed, all texts are internationalized

## Reviewer checklist
Reviewed by: @marla-singer @matleppa 

This list is to be completed by the pull request reviewer:
- [ ] Code works as described/expected
- [ ] Code seems to be error free
    - [ ] no browser console errors visible
    - [ ] no server console errors visible
    - [ ] passes CI build
- [ ] Code is written in a way that promotes maintainability
    - [ ] easy to understand
    - [ ] well organized
    - [ ] follows project coding standards and conventions
    - [ ] well documented

### CODE REVIEW

**Comment by matleppa** [comment]
### Good start
When an API having name with non-ascii alphabet is created, this seems to work fine. A converted slug is formed.

### However, 
Same functionality should apply when changing API name. A slug reflecting changed API name should be formed, same way as now happens with API names of ascii characters.

#### What happens now with non-ascii chars?
- add ascii part to non-ascii API name
  - slug is formed of only ascii part
    - should be formed based on complete name
- add non-ascii characters to API name previously with ascii characters
  - new slug is formed based on Roman character part of name (old: slug-for-romans, new: slug-for-romans-1)
    - should be formed based on complete name
- add non-ascii chars to name previously with non-ascii
  - the slug remains the same as earlier
    - should be formed based on complete name
  - exception in server log
```
Exception from sub apiComposite id QczwsBNFBkipA4gj7 Error: Match error: Expected string, got null
    at exports.check (packages\check.js:55:15)
    at [object Object].<anonymous> (apinf_packages/apis/collection/server/publications.js:57:3)
    at [object Object].prepareOptions (packages/reywood:publish-composite/lib/publish_composite.js:37:43)
    at [object Object].publish (packages/reywood:publish-composite/lib/publish_composite.js:12:48)
    at packages\matb33_collection-hooks.js:307:21
    at [object Object].EVp.withValue (packages\meteor.js:1135:15)
    at [object Object]._handler (packages\matb33_collection-hooks.js:306:28)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
    at packages/ddp-server/livedata_server.js:1043:15
    at [object Object].EVp.withValue (packages\meteor.js:1135:15)
    at [object Object]._.extend._runHandler (packages/ddp-server/livedata_server.js:1041:51)
    at [object Object]._.extend._startSubscription (packages/ddp-server/livedata_server.js:859:9)
    at [object Object]._.extend.protocol_handlers.sub (packages/ddp-server/livedata_server.js:625:12)
    at packages/ddp-server/livedata_server.js:559:43
Sanitized and reported to the client as: Match failed [400]

```
 - should be no exception

#### Exceptions also in other case 
Similar kind of exceptions is also generated 
1 open an API
2 select Add API (in main menu)

Here the probable cause may be missing check whether slug was gotten (around line 31 in apinf_packages\apis\client\profile\view.js)

**Comment by marla-singer** [comment]
@matleppa @deligence-dharmendra I put my two cents. 
The current solution will fix the future cases - if a user **will come** to a site and **will add** an API with no standard alphabet name. 

How does the implemented code fix the existing cases in apinf.io site? I meant does it need to add migration step to update existing slug parameters?

**Comment by matleppa** [comment]
@marla-singer @deligence-dharmendra 
Good point, the need of migration.
At the time in apinf.io there are two APIs with non-ascii chars in name: 
- openAPI测试 (slug: openapi)
  - although to slug is not formed of complete API name, it is unique and the API card can be opened. When also functionality of taken into account the non-ascii chars, when API name is changed and new slug is formed, is implemented and taken in use, this (or these) APIs' slug will be better in case the name is changed. 
-  特殊天 (no slug)
  - this API card can not be opened via UI, because of missing slug. 
  
So I think that the migration could go through all APIs and only in case the slug is **missing**, it forms one (of course checking, that the formed slug is unique).
@marla-singer Do you agree or do you find something missing?

**Comment by deligence-dharmendra** [comment]
Hi @matleppa 
what i'm getting point from you suggestion, if I'm not wrong.
1)eg:
 **API Name**     =>  **slug**
Activation and Configuration API  => activation-and-configuration-api
24Rent-yhteiskäyttöautot => 24rent-yhteiskaeyttoeautot
apinf要实现 => apinf-yao-shi-xian
特殊天 => te-shu-tian
要实现 Speaker => yao-shi-xian-speaker
 
Please advise

**Comment by matleppa** [comment]
@deligence-dharmendra Yes, same functionality concerning non-ascii char handling is needed both in creation on an API and changing of name of an existing API.

And also during migration.

**Comment by deligence-dharmendra** [comment]
Hi @matleppa @marla-singer 
I have implemented the functionality for creation and updation for ascii and non-ascii API name.
and it is working fine for me as per my understanding.But i'm getting issue with file apis/collection/slugs.js. 
Can i comment all code in this file.

Please advise

**Comment by marla-singer** [comment]
> Can i comment all code in this file.

Comment this file. If everything works fine without the standart slug and with "limax" packages then
1. Remove this file
2. Migrate the new slug implementation

Test the cases:
1. A user creates an API
2. A user updates the API

**Expected result**:
1. The name is updated successfully
2. The slug is updated successfully as well

Also the application supports slug for organizations. If the new slug implementation works well then migrate for organizaiont as well

**Comment by deligence-dharmendra** [comment]
Hi @marla-singer @matleppa 
Please review the latest changes . If everything on the right way,  then i will implement same functionality for the organization name.

**Comment by matleppa** [comment]
@deligence-dharmendra It seems, that we are going to right direction, however, I was able to find one problem.

API names has to be unique, and also slugs need to be unique.
Because the non-ascii chars in API name are mapped to ascii chars in different ways, it can happen, that the formed slug is not unique. One of those chars is 'å', which is mapped 'a'.
Previously this is avoided by adding a postfix into formed slug ( e.g. -1).

In nightly.apinf.io there is an example of old functionality:

**API name | slug**
AAA new API | aaa-new-api
ÅÅÅ new API | aaa-new-api-1

However there is a problem, when I'm using this branch and trying to create an API giving similar kind of names 
**API name | slug**
api | api
åpi |

When I press button [Add API], instead of creating API card and forming slug such as (api-1), nothing happens.

Same problem when changing API name.

File: apinf_packages/apis/server/methods/apiBackends.js [hunk 1]
```diff
@@ -27,4 +30,65 @@ Meteor.methods({
     // Return the API
     return api;
   },
+  updateSlug (apiId = null, name = null) {
+    let apiName = '';
+    if (apiId !== null) {
+      // Make sure Id is a string
+      check(apiId, String);
+      const api = Apis.findOne(apiId);
+      apiName = api.name;
```
Comment (matleppa) [inline apinf_packages/apis/server/methods/apiBackends.js]: Check if api exists.

File: apinf_packages/apis/server/methods/apiBackends.js [hunk 2]
```diff
@@ -27,4 +30,65 @@ Meteor.methods({
...
+    }
+
+    // Transliterates non-Latin scripts
+    const slug = slugs(apiName, { tone: false });
+
+    // Look for existing duplicate slug
+    const existingApi = Apis.findOne(
+      { 'friendlySlugs.slug.base':slug },
+      { sort: { created_at: -1 }},
+      { limit: 1 }
```
Comment (matleppa) [inline apinf_packages/apis/server/methods/apiBackends.js]: What is purpose of this parameter limit?

File: apinf_packages/apis/server/methods/apiBackends.js [hunk 3]
```diff
@@ -27,4 +30,65 @@ Meteor.methods({
...
+        return '';
+      }
+    } else {
+      return '';
+    }
+
+    // Transliterates non-Latin scripts
+    const slug = slugs(apiName, { tone: false });
+
+    // Look for existing duplicate slug
```
Comment (matleppa) [inline apinf_packages/apis/server/methods/apiBackends.js]: // Look for existing duplicate slug beginning of the newest one

File: apinf_packages/core/migrations/server/6-add-slug-for-apis.js [hunk 4]
```diff
@@ -7,7 +7,13 @@ Migrations.add({
   name: 'Adds the slug field for APIs document if it has not been created yet',
   up () {
     Apis.find({ slug: { $exists: false } }).forEach((api) => {
-      Apis.update(api._id);
+      if (api.name) {
```
Comment (marla-singer) [inline apinf_packages/core/migrations/server/6-add-slug-for-apis.js]: Never change the old steps of migration. There needs to save persistence instructions. In this case, the different APInf instances may have different behaviour of migration. 

**Create a new migration step**

**Comment by deligence-dharmendra** [comment]
Hi @marla-singer @matleppa 
1)I have created a new migration file:"12-add-slug-for-existing-apis" for slug api, and pushed changes to branch. But at the time of travis ci build, I'm getting error and not aware about those error.
**error like**
00 login
    1) "before all" hook
  0 passing (10s)
  1 failing
  1) 00 login "before all" hook:
     Uncaught unknown error: cannot determine loading status
    from unknown error: missing or invalid 'entry.level'

2)I have a doubt about migration version 6. I have implemented slug using new way and new package 'limax' and removed the existing file api slug.js. So it may be create issue at the time migration version 6  will call.

Please advise.

**Comment by marla-singer** [comment]
> So it may be create issue at the time migration version 6 will call.

@deligence-dharmendra Test it. But I don't see any dependences on the slug library in the 6 migration step

**Comment by marla-singer** [comment]
@deligence-dharmendra The PR contains the alien commits and it is hard to review.

1. make `git rebase develop` - it will place your commits on the current branch  top
2. Fix a conflict if it would be
3. make `git push -f`

File: apinf_packages/organizations/client/profile/settings/general/autoform.js [hunk 5]
```diff
@@ -11,11 +11,30 @@ import { sAlert } from 'meteor/juliancwirko:s-alert';
 AutoForm.hooks({
   organizationSettingsGeneral: {
     onSuccess () {
-      // Get success message translation
-      const message = TAPi18n.__('organizationSettingsGeneral_update_successMessage');
+      // Getting name from this.udateDoc
+      const orgName = this.updateDoc.$set.name;
+      if (orgName) {
+        Meteor.call('updateOrgSlug', null, orgName, (error, slug) => {
```
Comment (marla-singer) [inline apinf_packages/organizations/client/profile/settings/general/autoform.js]: Use the full name. 
org = organization
orgName = organizationName
updateOrgSlug = updateOrganizationSlug
and the same stuff

**Remake all short names**

File: apinf_packages/organizations/server/methods.js [hunk 6]
```diff
@@ -175,4 +178,79 @@ Meteor.methods({
 
     return userIsAdmin || userIsManager;
   },
+  updateOrgSlug (organizationId = null, name = null) {
```
Comment (marla-singer) [inline apinf_packages/organizations/server/methods.js]: Don't two parameters for function "updateOrgSlug" that are not both used at one time. I strongly recommend to use only one parameter - `query` that is the Object and will be `{ _id: organizationId }` or `{ name: organizationName }`.

Use it as
```js
const organization = Organizations.findOne(query);
```

File: apinf_packages/organizations/client/profile/settings/general/autoform.js (hunk 5 above)
Comment (marla-singer) [reply apinf_packages/organizations/client/profile/settings/general/autoform.js]: And after updating the function, call it as 
```js
Meteor.call('updateOrganizationSlug', { name: organizationName }, () => { .. });
```

File: apinf_packages/organizations/client/add/autoform.js [hunk 7]
```diff
@@ -41,14 +41,23 @@ AutoForm.hooks({
...
-        // Get reference to template instance
-        const instance = this;
-
-        // Get organization URL slug
-        const slug = instance.insertDoc.slug;
-
-        // Redirect to newly added organization
-        FlowRouter.go('organizationProfile', { slug });
+        if (organizationId) {
+          Meteor.call('updateOrgSlug', organizationId, null, (error, result) => {
```
Comment (marla-singer) [inline apinf_packages/organizations/client/add/autoform.js]: And after updating the function, call it as 
```js
Meteor.call('updateOrganizationSlug', { _id: organizationId }, () => { .. });
```

Comment (marla-singer) [inline apinf_packages/organizations/client/add/autoform.js]: And why do we need update slug if the organization was added? I think it is more logical to make if formType is update

**Comment by matleppa** [comment]
It was a good catch, that also Organization needs correction in forming the slug.

There is one matter, which need to be taken into account, because there is difference between APIs and Organizations.

API name must be unique, but Organization name needs not to be unique.

I tested the Organization slug functionality:
- create an Organization (name with non-ascii chars
  - creation OK, a translittered slug was formed 
- create second Organization **using same name**
  - new Organization was created, but without a slug. 
  - however, the slug of **first** Organization was changed (added index number)
- create third Organization **using same name**
  - new Organization was created, but without a slug. 
  - however, the slug of **first** Organization was changed (increased index number)

So a checking is needed, that slug of correct Organization is formed.

**Comment by Nazarah** [comment]
@matleppa apart from this PR, do you recommend that organizations have unique name?
That would be justifiable.
because if you consider normal cases like creating a new gmail ID, google checks that if a given ID already exists or taken and then it suggests an alternative one.

**Comment by matleppa** [comment]
@Nazarah Generally, to me it would sound logical, that also Organization names were unique. 

I am not familiar with previous decisions, what might have been the reason not to have unique Organization names.

**Comment by preriasusi** [comment]
Would it make sense to handle organisation changes in another issue? Or the issue of organisations name uniqueness in another issue? Feels too much for one.

**Comment by deligence-dharmendra** [comment]
Hi @preriasusi 
Do I need to work on same branch for organization slug or I need to create new branch for it.
Second thing I want to know Organization name needs to be unique or not. I think it should be unique. 

Please advise

**Comment by deligence-dharmendra** [comment]
Hi @preriasusi @marla-singer @matleppa @Nazarah 
Organization name needs to be unique or not?. I think it should be unique.

Please advise.

**Comment by matleppa** [comment]
I agree with unique Organization names.
Of course it means, that a migration is once again needed to make sure, that all already existing Organization names also are unique.

**Comment by deligence-dharmendra** [comment]
Hi @matleppa 
Can you suggest me, what step I need to do if organization duplicate name exists, I mean what suffix or prefix need to add.

Please advise

**Comment by matleppa** [comment]
I'd say that during migration the found duplicated names are separated with suffix.
-X, where X is increasing number.

Let's say there are three Organizations named "Fine Organization"

After migration they were:
Fine Organization
Fine Organization-1
Fine Organization-2

**Comment by deligence-dharmendra** [comment]
Hi @matleppa 
Below conversion made by Limax package, this scenario happened In only some language case like Chinese.

**特殊天-1 --> te-shu-tian1**

I have posted this issue on Limax GitHub repository. https://github.com/lovell/limax/issues/28
Please advise

**Comment by matleppa** [comment]
@deligence-dharmendra About the Limax issue: OK, fine. So the fix will probably come at some point. 
And this is the best we can do now.

File: apinf_packages/apis/server/methods/apiBackends.js [hunk 8]
```diff
@@ -27,11 +30,67 @@ Meteor.methods({
...
   },
-  getApiById (id) {
-    // Make sure slug is a string
-    check(id, String);
+  updateApisBySlug (query) {
+    // Make sure query is a object
+    check(query, Object);
+    const api = Apis.findOne(query);
+    if (!api) {
+      return '';
```
Comment (marla-singer) [inline apinf_packages/apis/server/methods/apiBackends.js]: Bad choose. If `api` doesn't exists with provided parameter then 

```js
throw new Meteor.Error(`The API doesn't exists with parameter ${query}`);
```

**Remake it**

File: apinf_packages/organizations/server/methods.js [hunk 9]
```diff
@@ -175,4 +178,68 @@ Meteor.methods({
 
     return userIsAdmin || userIsManager;
   },
+  updateOrganizationBySlug (query) {
+    // Make sure query is a object
+    check(query, Object);
+    const organization = Organizations.findOne(query);
+
+    if (!organization) {
+      return '';
```
Comment (marla-singer) [inline apinf_packages/organizations/server/methods.js]: Bad choose. If `organization` doesn't exist with provided parameter then 

```js
throw new Meteor.Error(`The Orgniazaiont doesn't exist with parameter ${query}`);
```

**Remake it**

File: apinf_packages/organizations/client/profile/settings/general/autoform.js [hunk 10]
```diff
@@ -3,19 +3,42 @@ This file is covered by the EUPL license.
...
+            // Redirect to newly added organization
+            FlowRouter.go('organizationProfile', { slug });
+          } else {
+            // Otherwise Redirect to Organization Catalog
+            FlowRouter.go('organizations');
+          }
+        });
+      } else {
+        // Otherwise Redirect to Organization Catalog
+        FlowRouter.go('organizations');
```
Comment (marla-singer) [inline apinf_packages/organizations/client/profile/settings/general/autoform.js]: The same stuff is here

If organizationName doesn't exist then **don't redirect to Organization Catalog**. Because a user can edit, for example, only Description field and in this case:
1. organizationName parameter doesn't exist
2. The page redirects to Catalog that is a wrong behavior because It expects to not change a page

**Remove this condition**

File: apinf_packages/apis/client/profile/settings/details/autoform.js [hunk 11]
```diff
@@ -11,14 +14,32 @@ import { FlowRouter } from 'meteor/kadira:flow-router';
...
-        FlowRouter.go('viewApi', { slug });
+      if (apiName) {
+        Meteor.call('updateApisBySlug', { name: apiName }, (error, slug) => {
+          if (error) {
+            // Show error message
+            sAlert.error(error);
+            FlowRouter.go('apiCatalog');
+          } else if (slug && slug !== '') {
+            // Redirect to modified api
+            FlowRouter.go('viewApi', { slug });
```
Comment (marla-singer) [inline apinf_packages/apis/client/profile/settings/details/autoform.js]: Simplify this code.

After improving `updateApisBySlug` function will return the `slug` value or throw error then

**Pseudocode**
1. If `error` then display a message and redirect to Catalog
2. If `slug` then redirect to Profile with new slug

**Remake**

File: apinf_packages/organizations/client/profile/settings/general/autoform.js [hunk 12]
```diff
@@ -3,19 +3,42 @@ This file is covered by the EUPL license.
...
-      // Get success message translation
-      const message = TAPi18n.__('organizationSettingsGeneral_update_successMessage');
+      // Getting name from this.udateDoc
+      const organizationName = this.updateDoc.$set.name;
+      if (organizationName) {
+        Meteor.call('updateOrganizationBySlug', { name: organizationName }, (error, slug) => {
+          if (error) {
+            // Show message
+            sAlert.error(error);
+          } else if (slug && slug !== '') {
```
Comment (marla-singer) [inline apinf_packages/organizations/client/profile/settings/general/autoform.js]: The same stuff is here

Simplify this code. After improving `updateOrganizationBySlug ` function will return the `slug` value or throw error then

**Pseudocode**
1. If `error` then display a message and redirect to Catalog
2. If `slug` then display a message and redirect to Profile with new slug

**Remake**

File: apinf_packages/apis/client/add/autoform.js [hunk 13]
```diff
@@ -29,15 +30,24 @@ AutoForm.hooks({
...
-          FlowRouter.go('apiCatalog');
-        }
-      });
+      if (apiId) {
+        Meteor.call('updateApisBySlug', { _id: apiId }, (error, result) => {
+          if (error) {
+            // Show message
+            sAlert.error(error);
+            FlowRouter.go('apiCatalog');
+          } else if (result && result !== '') {
```
Comment (marla-singer) [inline apinf_packages/apis/client/add/autoform.js]: 1. **Rename "result" variable to "slug"
2. Simplify this code. After improving `updateApisBySlug ` function will return the `slug` value or throw error then

**Pseudocode**
1. If `error` then display a message and redirect to Catalog
2. If `slug` then redirect to Profile with new slug

**Remake**

Comment (marla-singer) [reply apinf_packages/apis/client/add/autoform.js]: Actually, why do we need Update slug if a user just added an API?

File: apinf_packages/core/migrations/server/14-add-slug-for-existing-apis.js [hunk 14]
```diff
@@ -0,0 +1,27 @@
...
+
+// Meteor packages imports
+import { Meteor } from 'meteor/meteor';
+
+import { Migrations } from 'meteor/percolate:migrations';
+
+import Apis from '/apinf_packages/apis/collection';
+
+Migrations.add({
+  version: 14,
```
Comment (marla-singer) [inline apinf_packages/core/migrations/server/14-add-slug-for-existing-apis.js]: Up your version of Migration steps to one

File: apinf_packages/core/migrations/server/14-add-slug-for-existing-apis.js [hunk 15]
```diff
@@ -0,0 +1,27 @@
...
+  name: 'Adds the slug field for APIs document if it has not been created yet',
+  up () {
+    Apis.find({ slug: { $exists: false } }).forEach((api) => {
+      if (api.name) {
+        Meteor.call('updateApisBySlug', { name: api.name }, (error) => {
+          if (error) {
+            //  Show error messag
```
Comment (marla-singer) [inline apinf_packages/core/migrations/server/14-add-slug-for-existing-apis.js]: Why do you do it if no action happens?

1. If you want to sync call then 
```js
const call = Meteor.call('updateApisBySlug', { name: api.name });
```
2. If you don't need a sync call then
```js
Meteor.call('updateApisBySlug', { name: api.name });
```

**Remake it**

File: apinf_packages/core/migrations/server/16-add-slug-for-existing-organizations.js [hunk 16]
```diff
@@ -0,0 +1,27 @@
...
+
+Migrations.add({
+  version: 16,
+  name: 'Adds the slug field for Organizations document if it has not been created yet',
+  up () {
+    Organizations.find({ slug: { $exists: false } }).forEach((organization) => {
+      if (organization.name) {
+        Meteor.call('updateOrganizationBySlug', { name: organization.name }, (error) => {
+          if (error) {
+            //  Show error messag
```
Comment (marla-singer) [inline apinf_packages/core/migrations/server/16-add-slug-for-existing-organizations.js]: Why do you do it if no action happens?

1. If you want to sync call then 
```js
const call = Meteor.call('updateOrganizationBySlug', { name: organization.name });
```
2. If you don't need a sync call then
```js
Meteor.call('updateOrganizationBySlug', { name: organization.name });
```

**Remake it**

File: apinf_packages/apis/client/add/autoform.js (hunk 13 above)
Comment (deligence-dharmendra) [reply apinf_packages/apis/client/add/autoform.js]: Hi @marla-singer 
Actually, API does not have the slug value in the form field while inserting. So we need to add slug manually by calling this meteor call.

**Comment by marla-singer** [comment]
@matleppa Will merge it when a new release will be created
