### PR TITLE
Change branding schema of social media links

### LINKED ISSUE #3213: Social media icons and link don't appear when field values are modified and updated in Branding page
**Steps to Reproduce**: 
1. go to page: https://staging.apinf.io and login as admin
2. go to user>branding
3. Make sure all possible social media icons and links are present (Facebook, twitter and GitHub) or add them.
4. on the Social media section, deselect the Name field from the first social  media controller and click Update
5. (check the UI for social media icon in footer).
6. Now minimize the controller (the 1st controller Name field was deselected) and click Update
7. (check the UI for social media icon in footer).
8. Repeat step 6 again.
                    
**Outcome**:
On deselecting name field, the icon for that social media on footer gets broken in the UI.
On minimizing the controller, other social media icons starts to disappear or be broken.
On continuous minimization attempts, all social media icons get disappeared despite Branding page have those configured.
The icons reappear when the browser page is manually reloaded.
socialmediabranding

         
**Expected Behavior**:
If social media and their links are configured in branding page, they should appear properly in the footer, despite the above mentioned action has taken place in the associated UI.
                   
**Environment**:
Windows 10, Chrome browser (latest), APInf staging site (https://staging.apinf.io)

### PR DESCRIPTION
**Pull request by marla-singer**
Closes #3213

## Changes
- Create a new migration step 12
- Create a new template footerSocialMediaLinks to display the social media icons in the footer
- Changes in en.i18n.json
- Changes on the Branding page
- Changes in the Branding schema

## Developer checklist
This checklist is to be completed by the PR developer:

- [ ] Alternative solutions were compared/discussed before writing code
    - [ ] trade-offs with this solution are considered acceptable
- [ ] Code in this PR adheres to the [project styleguide](CONTRIBUTING.md)
- [ ] This pull request does not decrease project test coverage
- [ ] If the code changes existing database collection(s), migration has been written
- [ ] If UI texts are added or changed, all texts are internationalized

## Reviewer checklist
Reviewed by: @55 @matleppa 

This list is to be completed by the pull request reviewer:
- [ ] Code works as described/expected
- [ ] Code seems to be error free
    - [ ] no browser console errors visible
    - [ ] no server console errors visible
    - [ ] passes CI build
- [ ] Code is written in a way that promotes maintainability
    - [ ] easy to understand
    - [ ] well organized
    - [ ] follows project coding standards and conventions
    - [ ] well documented

### CODE REVIEW

File: apinf_packages/core/migrations/server/12-change-branding-schema.js [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+    const branding = Branding.findOne();
+
+    // Make sure Configuration exists
+    if (branding) {
+      // Go through all social media
+      branding.socialMedia.forEach(social => {
+        // Lower case the name
+        const socialName = social.name.toLowerCase();
+
+        // Make sure it is not duplicate of existing social media
```
Comment (matleppa) [inline apinf_packages/core/migrations/server/12-change-branding-schema.js]: What about the case, that there are empty items in socialMedia array?

Check if socialName exists before handling the socialMediaLinks.

Comment (marla-singer) [reply apinf_packages/core/migrations/server/12-change-branding-schema.js]: If the array is empty then the loop will not run

Comment (matleppa) [reply apinf_packages/core/migrations/server/12-change-branding-schema.js]: The problem arises in case the array is not empty, but there are empty items in it. 
Here is a console log displaying Branding object.

I20171214-10:57:16.012(2) (packages\logging.js:101) Migrations: Running up() on version 12 (Change branding schema: migrate to new schema for social media urls)
I20171214-10:57:16.126(2)? branding= Document {
I20171214-10:57:16.139(2)?   _id: 'qQyGcb5xCzAirem2L',
I20171214-10:57:16.140(2)?   siteTitle: 'A mediocre site',
I20171214-10:57:16.142(2)?   siteSlogan: 'A mediocrazy site is this.',
I20171214-10:57:16.144(2)?   siteFooter: 'Put site footer here',
I20171214-10:57:16.147(2)?   coverPhotoFileId: '335017ab44ba8184ffc97d32',

Two empty items in socialMedia array, followed by one filled item.

I20171214-10:57:16.148(2)?   socialMedia: [ null, null, { name: 'Twitter', url: 'https://Twitter.com' } ],


I20171214-10:57:16.149(2)?   projectLogoFileId: '0451e92216d97d1beebab6fc',
I20171214-10:57:16.154(2)?   privacyPolicy: '<div><br></div>',
I20171214-10:57:16.155(2)?   termsOfUse: '<div><br></div>' }

Result:

W20171214-10:57:16.216(2)? (STDERR) TypeError: Cannot read property 'name' of null
W20171214-10:57:16.219(2)? (STDERR)     at apinf_packages/core/migrations/server/12-change-branding-schema.js:26:28
W20171214-10:57:16.220(2)? (STDERR)     at Array.forEach (native)
W20171214-10:57:16.222(2)? (STDERR)     at Object.Migrations.add.up (apinf_packages/core/migrations/server/12-change-branding-schema.js:24:28)
W20171214-10:57:16.224(2)? (STDERR)     at migrate (packages\percolate_migrations.js:233:25)
W20171214-10:57:16.226(2)? (STDERR)     at Object.Migrations._migrateTo (packages\percolate_migrations.js:253:7)
W20171214-10:57:16.229(2)? (STDERR)     at Object.Migrations.migrateTo (packages\percolate_migrations.js:167:10)
W20171214-10:57:16.232(2)? (STDERR)     at apinf_packages/core/migrations/server/startup.js:13:14
W20171214-10:57:16.246(2)? (STDERR)     at Function.time (C:\Users\matleppa\api\apinf\platform\.meteor\local\build\programs\server\profile.js:309:28)
W20171214-10:57:16.248(2)? (STDERR)     at C:\Users\matleppa\api\apinf\platform\.meteor\local\build\programs\server\boot.js:347:13
W20171214-10:57:16.251(2)? (STDERR)     at C:\Users\matleppa\api\apinf\platform\.meteor\local\build\programs\server\boot.js:388:5
W20171214-10:57:16.258(2)? (STDERR)     at Function.run (C:\Users\matleppa\api\apinf\platform\.meteor\local\build\programs\server\profile.js:510:12)
W20171214-10:57:16.261(2)? (STDERR)     at C:\Users\matleppa\api\apinf\platform\.meteor\local\build\programs\server\boot.js:386:11
=> Exited with code: 1

----------------
I did not need to generate it artificially ;-)

**Comment by marla-singer** [comment]
@matleppa Fixed
