### PR TITLE
fixed issue Browser tab shows different message instead "APInf" name #2591

### LINKED ISSUE #2591: Browser tab shows different message instead "APInf" name
# Reproduction Step

* Go to apinf.io 
* Look at Browser Tab (or hover the mouse on it)

# Result
"Get Control of your digital resource" message appears on browser tab and tool tip
image

# System
* Windows 8
* Chrome (latest)

# Suggestion
* "APInf - Develop. We do the REST." this message sound more suitable to appear on browser tab.
This represents both our Platform name and slogan.
* the current message can also be kept with "- APInf" inserted as suffix (check homepages of [Dropbox Business](https://www.dropbox.com/business), [Airbnb](https://www.airbnb.com/) in browser tab for example.)

### PR DESCRIPTION
**Pull request by saransh-dev**
Closes #2591 

## Changes
- Set title of every page from onCreated of each parent template

## Developer checklist
This checklist is to be completed by the PR developer:

- [ ] Alternative solutions were compared/discussed before writing code
    - [ ] trade-offs with this solution are considered acceptable
- [ ] Code in this PR adheres to the [project styleguide](CONTRIBUTING.md)
- [ ] This pull request does not decrease project test coverage
- [ ] If the code changes existing database collection(s), migration has been written
- [ ] If UI texts are added or changed, all texts are internationalized

## Reviewer checklist
Reviewed by: @marla-singer @Nazarah 

This list is to be completed by the pull request reviewer:
- [ ] Code works as described/expected
- [ ] Code seems to be error free
    - [ ] no browser console errors visible
    - [ ] no server console errors visible
    - [ ] passes CI build
- [ ] Code is written in a way that promotes maintainability
    - [ ] easy to understand
    - [ ] well organized
    - [ ] follows project coding standards and conventions
    - [ ] well documented

### CODE REVIEW

File: apinf_packages/api_catalog/client/api_catalog.js [hunk 1]
```diff
@@ -26,6 +28,19 @@ Template.apiCatalog.onCreated(function () {
...
+  instance.autorun(() => {
+    // Check for template subscriptions
+    if (instance.subscriptionsReady) {
+      // Get Branding collection content
+      const branding = Branding.findOne();
+      // Check if Branding collection and siteTitle are available
+      if (branding && branding.siteTitle) {
+        // Set the page title
+        const title = branding.siteTitle;
+        DocHead.setTitle(`${title} - APIs Catalog`);
```
Comment (55) [inline apinf_packages/api_catalog/client/api_catalog.js]: i18n

File: apinf_packages/apis/client/add/add.js [hunk 2]
```diff
@@ -6,9 +6,31 @@ https://joinup.ec.europa.eu/community/eupl/og_page/european-union-public-licence
...
+  instance.autorun(() => {
+    // Check for template subscriptions
+    if (instance.subscriptionsReady) {
+      // Get Branding collection content
+      const branding = Branding.findOne();
+      // Check if Branding collection and siteTitle are available
+      if (branding && branding.siteTitle) {
+        // Set the page title
+        const title = branding.siteTitle;
+        DocHead.setTitle(`${title} - Add API`);
```
Comment (55) [inline apinf_packages/apis/client/add/add.js]: i18n

File: apinf_packages/branding/client/branding.js [hunk 3]
```diff
@@ -22,6 +23,19 @@ Template.branding.onCreated(function () {
...
+  templateInstance.autorun(() => {
+    // Check for template subscriptions
+    if (templateInstance.subscriptionsReady) {
+      // Get Branding collection content
+      const branding = Branding.findOne();
+      // Check if Branding collection and siteTitle are available
+      if (branding && branding.siteTitle) {
+        // Set the page title
+        const title = branding.siteTitle;
+        DocHead.setTitle(`${title} - Branding`);
```
Comment (55) [inline apinf_packages/branding/client/branding.js]: i18n

File: apinf_packages/dashboard/client/dashboard.js [hunk 4]
```diff
@@ -9,16 +9,32 @@ import { ReactiveVar } from 'meteor/reactive-var';
...
+  instance.autorun(() => {
+    // Check for template subscriptions
+    if (instance.subscriptionsReady) {
+      // Get Branding collection content
+      const branding = Branding.findOne();
+      // Check if Branding collection and siteTitle are available
+      if (branding && branding.siteTitle) {
+        // Set the page title
+        const title = branding.siteTitle;
+        DocHead.setTitle(`${title} - Dashboard`);
```
Comment (55) [inline apinf_packages/dashboard/client/dashboard.js]: i18n

File: apinf_packages/login_platforms/client/login_platforms.js [hunk 5]
```diff
@@ -6,12 +6,30 @@ https://joinup.ec.europa.eu/community/eupl/og_page/european-union-public-licence
...
+  instance.autorun(() => {
+    // Check for template subscriptions
+    if (instance.subscriptionsReady) {
+      // Get Branding collection content
+      const branding = Branding.findOne();
+      // Check if Branding collection and siteTitle are available
+      if (branding && branding.siteTitle) {
+        // Set the page title
+        const title = branding.siteTitle;
+        DocHead.setTitle(`${title} - Login Platforms`);
```
Comment (55) [inline apinf_packages/login_platforms/client/login_platforms.js]: i18n

File: apinf_packages/organizations/client/catalog/catalog.js [hunk 6]
```diff
@@ -23,6 +25,20 @@ Template.organizationCatalog.onCreated(function () {
...
+  instance.autorun(() => {
+    // Check for template subscriptions
+    if (instance.subscriptionsReady) {
+      // Get Branding collection content
+      const branding = Branding.findOne();
+      // Check if Branding collection and siteTitle are available
+      if (branding && branding.siteTitle) {
+        // Set the page title
+        const title = branding.siteTitle;
+        DocHead.setTitle(`${title} - Organizations Catalog`);
```
Comment (55) [inline apinf_packages/organizations/client/catalog/catalog.js]: i18n

File: apinf_packages/proxies/client/proxies.js [hunk 7]
```diff
@@ -7,14 +7,28 @@ https://joinup.ec.europa.eu/community/eupl/og_page/european-union-public-licence
...
+  instance.autorun(() => {
+    // Check for template subscriptions
+    if (instance.subscriptionsReady) {
+      // Get Branding collection content
+      const branding = Branding.findOne();
+      // Check if Branding collection and siteTitle are available
+      if (branding && branding.siteTitle) {
+        // Set the page title
+        const title = branding.siteTitle;
+        DocHead.setTitle(`${title} - Proxies`);
```
Comment (55) [inline apinf_packages/proxies/client/proxies.js]: i18n

File: apinf_packages/settings/client/settings.js [hunk 8]
```diff
@@ -6,12 +6,31 @@ https://joinup.ec.europa.eu/community/eupl/og_page/european-union-public-licence
...
+  instance.autorun(() => {
+    // Check for template subscriptions
+    if (instance.subscriptionsReady) {
+      // Get Branding collection content
+      const branding = Branding.findOne();
+      // Check if Branding collection and siteTitle are available
+      if (branding && branding.siteTitle) {
+        // Set the page title
+        const title = branding.siteTitle;
+        DocHead.setTitle(`${title} - Settings`);
```
Comment (55) [inline apinf_packages/settings/client/settings.js]: i18n

File: apinf_packages/users/client/account/account.js [hunk 9]
```diff
@@ -7,8 +7,32 @@ https://joinup.ec.europa.eu/community/eupl/og_page/european-union-public-licence
...
+  instance.autorun(() => {
+    // Check for template subscriptions
+    if (instance.subscriptionsReady) {
+      // Get Branding collection content
+      const branding = Branding.findOne();
+      // Check if Branding collection and siteTitle are available
+      if (branding && branding.siteTitle) {
+        // Set the page title
+        const title = branding.siteTitle;
+        DocHead.setTitle(`${title} - Account`);
```
Comment (55) [inline apinf_packages/users/client/account/account.js]: i18n

File: apinf_packages/users/client/profile/profile.js [hunk 10]
```diff
@@ -7,6 +7,30 @@ https://joinup.ec.europa.eu/community/eupl/og_page/european-union-public-licence
...
+  instance.autorun(() => {
+    // Check for template subscriptions
+    if (instance.subscriptionsReady) {
+      // Get Branding collection content
+      const branding = Branding.findOne();
+      // Check if Branding collection and siteTitle are available
+      if (branding && branding.siteTitle) {
+        // Set the page title
+        const title = branding.siteTitle;
+        DocHead.setTitle(`${title} - Profile`);
```
Comment (55) [inline apinf_packages/users/client/profile/profile.js]: i18n

**Comment by 55** [comment]
@marla-singer or @matleppa please review the code.

File: apinf_packages/settings/client/settings.js [hunk 11]
```diff
@@ -6,12 +6,32 @@ https://joinup.ec.europa.eu/community/eupl/og_page/european-union-public-licence
...
 // Collection imports
+import Branding from '/apinf_packages/branding/collection';
 import Settings from '/apinf_packages/settings/collection';
 
 Template.settings.onCreated(function () {
+  const instance = this;
+
+  instance.autorun(() => {
+    // Check for template subscriptions
+    if (instance.subscriptionsReady) {
```
Comment (marla-singer) [inline apinf_packages/settings/client/settings.js]: The same stuff is here
1. Don't see profit from this check because you use another checking below. 
**Remove this "if"**

2. 
```js
const pageTitle = TAPi18n.__(...);
DocHead.setTitle(`${branding.title} - ${pageTitle}`);
```
**Remade**

File: apinf_packages/users/client/account/account.js [hunk 12]
```diff
@@ -7,7 +7,32 @@ https://joinup.ec.europa.eu/community/eupl/og_page/european-union-public-licence
...
 // Meteor contributed packages imports
+import { DocHead } from 'meteor/kadira:dochead';
 import { Modal } from 'meteor/peppelg:bootstrap-3-modal';
+import { TAPi18n } from 'meteor/tap:i18n';
+
+// Collection imports
+import Branding from '/apinf_packages/branding/collection';
+
+
+Template.account.onCreated(function () {
```
Comment (marla-singer) [inline apinf_packages/users/client/account/account.js]: We use 1 empty line as separation

**Remove needless 1 empty line**

File: apinf_packages/users/client/account/account.js [hunk 13]
```diff
@@ -7,7 +7,32 @@ https://joinup.ec.europa.eu/community/eupl/og_page/european-union-public-licence
...
+	// Get reference to template instance
+  const instance = this;
+
+  instance.autorun(() => {
+    // Check for template subscriptions
+    if (instance.subscriptionsReady) {
```
Comment (marla-singer) [inline apinf_packages/users/client/account/account.js]: The same stuff is here
1. Don't see profit from this check because you use another checking below. 
**Remove this "if"**

2. 
```js
const pageTitle = TAPi18n.__(...);
DocHead.setTitle(`${branding.title} - ${pageTitle}`);
```
**Remade**

File: apinf_packages/users/client/profile/profile.js [hunk 14]
```diff
@@ -7,6 +7,33 @@ https://joinup.ec.europa.eu/community/eupl/og_page/european-union-public-licence
...
 
+// Meteor contributed packages imports
+import { DocHead } from 'meteor/kadira:dochead';
+import { TAPi18n } from 'meteor/tap:i18n';
+
+// Collection imports
+import Branding from '/apinf_packages/branding/collection';
+
+
+Template.profile.onCreated(function () {
```
Comment (marla-singer) [inline apinf_packages/users/client/profile/profile.js]: We use 1 empty line as separation

**Remove needless 1 empty line**

File: apinf_packages/users/client/profile/profile.js [hunk 15]
```diff
@@ -7,6 +7,33 @@ https://joinup.ec.europa.eu/community/eupl/og_page/european-union-public-licence
...
+  // Get reference to template instance
+  const instance = this;
+
+  instance.autorun(() => {
+    // Check for template subscriptions
+    if (instance.subscriptionsReady) {
```
Comment (marla-singer) [inline apinf_packages/users/client/profile/profile.js]: The same stuff is here
1. Don't see profit from this check because you use another checking below. 
**Remove this "if"**

2. 
```js
const pageTitle = TAPi18n.__(...);
DocHead.setTitle(`${branding.title} - ${pageTitle}`);
```
**Remade**

**Comment by marla-singer** [comment]
@saransh-dev Too much commits. Please rebase your branch and leave only one commit

A little lifehack: Before commit your changes run linter on local using command `npm run lint` or `yarn lint`. It allows you to see style remarks **before** you will push it to remote branch and before travis checking
