### PR TITLE
Hotfix/api feedback form

### LINKED ISSUE #1525: Feedback form not working properly
When submitting the Feedback form, the page is reloaded instead of properly submitting. In addition, rendering the Feedback form produces several console errors.

### PR DESCRIPTION
**Pull request by frenchbread**
Closes #1525.

### CODE REVIEW

File: feedback/client/form/autoform.js [hunk 1]
```diff
@@ -9,6 +9,7 @@ AutoForm.hooks({
     },
     onSuccess () {
       sAlert.success('Thank you! Your feedback has been successfully sent.');
```
Comment (brylie) [inline feedback/client/form/autoform.js]: Add i18n token here.

**Comment by bajiat** [comment]
@nnn Re-assigning Brylie for the PR review, because we would need to get this forward and there has been no visible activity in discussion.

File: feedback/client/form/form.html [hunk 2]
```diff
@@ -1,24 +1,24 @@
...
-        </div>
-        <div class="modal-body">
-          <p>{{_ "feedback_feedbackForm_description"}}</p>
-          {{> quickForm
-            collection=feedbackCollection
-            id="feedbackForm"
-            type="insert"
-            omitFields="authorId, createdAt, apiBackendId"
-          }}
+          <h4 class="modal-title" id="feedbackFormModalLabel">{{_ "feedback_feedbackForm_title"}}</h4>
```
Comment (brylie) [inline feedback/client/form/form.html]: Break this into nested lines, for readability and to shorten the line length:

```html
<h4 class="modal-title" id="feedbackFormModalLabel">
  {{_ "feedback_feedbackForm_title"}}
</h4>
```

File: feedback/client/form/form.html [hunk 3]
```diff
@@ -1,24 +1,24 @@
 <template name="feedbackForm">
-  <button type="button" class="btn btn-info btn-xs pull-right feedback-form-button" data-toggle="modal" data-target="#feedbackForm" data-backdrop="static" data-keyboard="false"><i class="fa fa-comments-o"></i>&nbsp;{{_ "feedback_feedbackForm_button"}}</button>
-  <div class="modal fade" id="feedbackForm" tabindex="-1" role="dialog" aria-labelledby="feedbackFormLabel">
+  <div class="modal fade" id="feedbackFormModal" tabindex="-1" role="dialog" aria-labelledby="feedbackFormModalLabel">
     <div class="modal-dialog" role="document">
       <div class="modal-content">
         <div class="modal-header">
           <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
```
Comment (brylie) [inline feedback/client/form/form.html]: Add nesting here, to improve readability and shorten the line length.

```html
<button type="button" class="close" data-dismiss="modal" aria-label="Close">
  <span aria-hidden="true">&times;</span>
</button>
```

**Comment by brylie** [comment]
This looks good. There is just one missing i18n string and some markup lint. I can merge this today, if you can make the suggested changes in the next 30 minutes.

**Comment by frenchbread** [comment]
Suggested changes are done. Please review

File: feedback/client/form/autoform.js [hunk 4]
```diff
@@ -8,7 +8,7 @@ AutoForm.hooks({
       },
     },
     onSuccess () {
-      sAlert.success('Thank you! Your feedback has been successfully sent.');
+      sAlert.success(TAPi18n.__('feedbackForm_successMessage'));
```
Comment (brylie) [inline feedback/client/form/autoform.js]: While this line is compact, it does not follow convention for other translated user alerts.

Refactor the code to follow this pattern:

```js
// Get the success message translation
const message = TAPi18n.__('feedbackForm_successMessage');

// Alert the user of success
sAlert.success(message);
```

The reason is to make lines of code easier to read:
- shorter lines
- `sAlert.success(message)` is very close to English 'alert success message'

Search for other uses of `sAlert` in our project, to get a sense of how it is typically used.

Comment (frenchbread) [inline feedback/client/form/autoform.js]: You've commented on an outdated diff. That file has already been changed.
