### PR TITLE
Fill value for updates_by field either from inputted value or from …

### LINKED ISSUE #3151: PUT /apis Error: Meteor.userId can only be invoked in method calls or publications
## Description

Method PUT fails

### Environment
Postman testing
Catalog API, method PUT

##### Note! Replaced previous erroneous  (unrelated, copy-paste error by me) errors with correct one

Error: Meteor.userId can only be invoked in method calls or publications.
    at AccountsServer.userId (packages/accounts-base/accounts_server.js:79:13)
    at Object.Meteor.userId (packages/accounts-base/accounts_common.js:263:19)
    at Object.Apis.schema.SimpleSchema.updated_by.autoValue (apinf_packages/apis/collection/schema.js:104:27)
    at Object.runAV (packages\aldeed_simple-schema.js:1282:26)
    at packages\aldeed_simple-schema.js:1383:13
    at Array.forEach (native)
    at Function._.each._.forEach (packages\underscore.js:139:11)
    at packages\aldeed_simple-schema.js:1382:7
    at Function._.each._.forEach (packages\underscore.js:147:22)
    at [object Object].getAutoValues (packages\aldeed_simple-schema.js:1345:5)
    at [object Object].SimpleSchema.clean (packages\aldeed_simple-schema.js:1763:42)
    at doClean (packages\aldeed_collection2-core.js:350:12)
    at [object Object].doValidate (packages\aldeed_collection2-core.js:372:3)
    at [object Object].Mongo.Collection.(anonymous function) [as update] (packages\aldeed_collection2-core.js:214:25)
    at Object.CatalogV1.addCollection.endpoints.put.action (apinf_packages/apis/server/api.js:668:14)
    at Route.share.Route.Route._callEndpoint (packages/nimble_restivus/lib/route.coffee:149:25)
    at packages/nimble_restivus/lib/route.coffee:59:33
    at packages\simple_json-routes.js:98:9

### Result in nightly
 500 Internal Server Error

### Testing with Swagger

	TypeError: Failed to fetch

### PR DESCRIPTION
**Pull request by matleppa**
…Meteor users

Closes #3151

## Changes
Changes in REST API Catalog API:
- POST /apis
  - convey user ID to created_by field in document in apis collection
- PUT /apis
  - convey user ID to updated_by field in document in apis collection
  - refactoring in decision about documentation update/create

- apis schema
  - autovalue function in field updated_by takes value either from inputted value or from Meteor.users

## Developer checklist
This checklist is to be completed by the PR developer:

- [ ] Alternative solutions were compared/discussed before writing code
    - [ ] trade-offs with this solution are considered acceptable
- [ ] Code in this PR adheres to the [project styleguide](CONTRIBUTING.md)
- [ ] This pull request does not decrease project test coverage
- [ ] If the code changes existing database collection(s), migration has been written
- [ ] If UI texts are added or changed, all texts are internationalized

## Reviewer checklist
Reviewed by: @username1

This list is to be completed by the pull request reviewer:
- [ ] Code works as described/expected
- [ ] Code seems to be error free
    - [ ] no browser console errors visible
    - [ ] no server console errors visible
    - [ ] passes CI build
- [ ] Code is written in a way that promotes maintainability
    - [ ] easy to understand
    - [ ] well organized
    - [ ] follows project coding standards and conventions
    - [ ] well documented

### CODE REVIEW

File: apinf_packages/apis/collection/schema.js [hunk 1]
```diff
@@ -101,7 +101,7 @@ Apis.schema = new SimpleSchema({
     autoValue () {
       let updateBy;
       if (this.isUpdate) {
-        updateBy = Meteor.userId();
+        updateBy = this.value || Meteor.userId();
```
Comment (marla-singer) [inline apinf_packages/apis/collection/schema.js]: Make the same for "created_by" field

**Comment by marla-singer** [comment]
@matleppa I restarted build but it still fails with the test. The code changes couldn't influence testing. Nevertheless, merge it
