### PR TITLE
[#3060] Register fiware account

### LINKED ISSUE #3060: Nightly FIWARE registration fails because of email verification
# Steps to reproduce
1. Create an account to FIWARE Lab: https://account.lab.fiware.org/
Note: Please use an email you are not already using for APInf
2. Go to nightly.apinf.io
3. Press Sign up link
4. Press Register with FIWARE
5. In the Fiware Lab window that open, give your user credentials for FIWARE Lab and authorize APInf

# Expected result
User is registered to APInf and can sign in with the FIWARE credentials. No email verification should be done (compare with Github registration).

# Actual result
User gets a notification about Email being sent to user. User never gets an email to their mail and thus user cannot sign in. If user tries to sign in, they get the same notification about email.

nightly-fiware-register-usernotification

### PR DESCRIPTION
**Pull request by mauriciovieira**
Closes #3060

## Changes
- Register fiware username just like github does

## Developer checklist
This checklist is to be completed by the PR developer:

- [ ] Alternative solutions were compared/discussed before writing code
    - [ ] trade-offs with this solution are considered acceptable
- [ ] Code in this PR adheres to the [project styleguide](CONTRIBUTING.md)
- [ ] This pull request does not decrease project test coverage
- [ ] If the code changes existing database collection(s), migration has been written
- [ ] If UI texts are added or changed, all texts are internationalized

## Reviewer checklist
Reviewed by: @username1

This list is to be completed by the pull request reviewer:
- [ ] Code works as described/expected
- [ ] Code seems to be error free
    - [ ] no browser console errors visible
    - [ ] no server console errors visible
    - [ ] passes CI build
- [ ] Code is written in a way that promotes maintainability
    - [ ] easy to understand
    - [ ] well organized
    - [ ] follows project coding standards and conventions
    - [ ] well documented

### CODE REVIEW

File: apinf_packages/users/server/accounts_hooks.js [hunk 1]
```diff
@@ -15,43 +15,49 @@ Accounts.onCreateUser((options, user) => {
 
   // Check services object exists
   if (user.services) {
-
     // Get the service, can be 'github', 'fiware' or 'password'
-    const service =  _.keys(user.services)[0];
+    const service = Object.keys(user.services)[0];
```
Comment (mauriciovieira) [inline apinf_packages/users/server/accounts_hooks.js]: 😍

File: apinf_packages/users/server/accounts_hooks.js [hunk 2]
```diff
@@ -15,43 +15,49 @@ Accounts.onCreateUser((options, user) => {
...
+
+        // Set service email to user email
+        user.emails = [
+          currentRegisteringEmail,
+        ];
       } else {
-        // Username clashes with existing username
-        user.username = `gh-${username}`;
+        // Get username prefix based on service being used
+        const prefix = service === 'github' ? 'gh' : 'fw';
```
Comment (mauriciovieira) [inline apinf_packages/users/server/accounts_hooks.js]: Good idea, but I'm thinking if we could have a more generic idea. 

Since we already have 'gh-' as a prefix, the other prefix should be 'oauth', or something like, and then we can easily add twitter, facebook, or whatever to authentication later.

Comment (midyan) [reply apinf_packages/users/server/accounts_hooks.js]: Maybe we can have a static dictionary object like so:

```javascript
const servicePrefixDictionary = {
    fiware: 'fw',
    github: 'gh',
    twitter: 'tw',
    facebook: 'fb',
};

user.username = `${servicePrefixDictionary[service]}-${username}`;
```

That way we can know exactly which OAuth has been used and we can avoid overloading the logic complexity with too many `else if`s

**Comment by midyan** [comment]
@mauriciovieira I have changed prefix logic a little to use a static dictionary object. Please, review everything and let me know you any changes are necessary

File: apinf_packages/users/server/accounts_hooks.js [hunk 3]
```diff
@@ -9,37 +9,63 @@ import { Meteor } from 'meteor/meteor';
 // Meteor contributed packages imports
 import { Accounts } from 'meteor/accounts-base';
 
+// OAuth Services dictionary to get the correct prefix
+const servicePrefixDictionary = {
+  fiware: 'fw',
+  github: 'gh',
+  twitter: 'tw',
```
Comment (55) [inline apinf_packages/users/server/accounts_hooks.js]: Why do we need to include twitter & facebook here?

Comment (midyan) [reply apinf_packages/users/server/accounts_hooks.js]: You are correct, there is no need at the moment. I should have removed those properties.

**Comment by 55** [comment]
@manzapanza @mauriciovieira should we merge it?
