### PR TITLE
API Import remake

### LINKED ISSUE #2945: Design user flow for exporting and importing API configuration
Our API Profile view currently has a tab where API owners can export API and Proxy settings. There is also a (currently broken) import page, which was designed for importing API settings (not proxy settings).

# Goals
- Allow users to easily export and import their API and Proxy settings.
  - Make exporting and importing easy to discover.
- Have a simple user experience related to exporting and importing API and Proxy settings. 
- Keep in mind the current user flow for adding an API, and offer an option to 'import existing API' during that process.

### PR DESCRIPTION
**Pull request by Vellames**
Closes #2945, #2943, #2912, #3053 

- [x] Change front-end import
- [x] Do the import flow without ShareJS (Ace editor)
- [x] Remove ShareJS for project
- [x] Fix API import error
- [x] Validate unique names and valid urls
- [x] Fix redirect after import successful 

WIP

### CODE REVIEW

**Comment by Vellames** [comment]
api-import

@brylie What do you think about this?

**Comment by brylie** [comment]
@Vellames it looks good! Is PR ready for review?

**Comment by Vellames** [comment]
`@Vellames it looks good! Is PR ready for review?`

Nops, i will remove the ShareJS and fix a problem in backend

**Comment by Vellames** [comment]
@brylie Almost done, i fixed the api imports backend and now the import works
The config.json must be something like this:
{
	"name": "Test Import API",
	"description": "hi",
	"url": "https://github.com/apinf/platform/pull/2973",
	"lifecycleStatus": "testing"
}

It's ok for you?
I think we could accept multiple APIs in JSON, What do you think?

I will add some verifications in method and fix some little bugs before send for review

File: apinf_packages/apis/server/methods/config.js [hunk 1]
```diff
@@ -12,40 +12,25 @@ import Apis from '/apinf_packages/apis/collection';
...
   };
+  const possiblesLifecycleStatus = ['design', 'develop', 'testing', 'production', 'deprecated'];
 
-  // iterates through object keys and checks if required fields are provided
-  // otherwise returns a message with missing field
-
-  if (Object.prototype.hasOwnProperty.call(jsonObj, '_id')) {
-    status.message += "'_id' field is not allowed to import.";
+  // Basic check fields:
+  if (!Object.prototype.hasOwnProperty.call(jsonObj, 'name')) {
```
Comment (brylie) [inline apinf_packages/apis/server/methods/config.js]: For what it's worth, we can [use SimpleSchema to validate JSON objects](https://github.com/aldeed/meteor-simple-schema#validating-data), with the same schema that validates collection data:

https://github.com/apinf/platform/blob/1cb628d3c1a9866962e3a2d76308c90feeedae82/apinf_packages/apis/collection/schema.js#L12

**Comment by Vellames** [comment]
@brylie 
1- Dependence removed
2- I use the SimpleSchema but it not verifies the unique constraint, so i did a find to check
3- How you do to apply i18n in SimpleSchema.validate()?

I will apply the i18n in the rest of api import after your review, ok?

**Comment by marla-singer** [comment]
> How you do to apply i18n in SimpleSchema.validate()?

@Vellames Why did you decide to validate i18n?

**Comment by brylie** [comment]
We don't really need to validate any i18n texts here. Just validating the import document with `SimpleSchema.validate()` should suffice.

File: apinf_packages/apis/client/import/import.js [hunk 2]
```diff
@@ -6,141 +6,100 @@ https://joinup.ec.europa.eu/community/eupl/og_page/european-union-public-licence
...
-  // keep current template instance
-  const instance = this;
+// Store the value inside the input file
+const apiConfiguration = new ReactiveVar();
 
-  // initialises ace editor
-  instance.editor = ace.edit('editor');
+Template.importApiConfiguration.onCreated(() => {
+  // Create the apiConfiguration variable
+  apiConfiguration.set('aaa');
```
Comment (brylie) [inline apinf_packages/apis/client/import/import.js]: Why do you set this to 'aaa'?

File: apinf_packages/apis/client/import/import.js [hunk 3]
```diff
@@ -6,141 +6,100 @@ https://joinup.ec.europa.eu/community/eupl/og_page/european-union-public-licence
...
 import { sAlert } from 'meteor/juliancwirko:s-alert';
 
 // Npm packages imports
 import jsyaml from 'js-yaml';
 
-Template.importApiConfiguration.onRendered(function () {
-  // keep current template instance
-  const instance = this;
+// Store the value inside the input file
+const apiConfiguration = new ReactiveVar();
```
Comment (brylie) [inline apinf_packages/apis/client/import/import.js]: We typically attach reactive variables to a Template instance. That way the reactive variable is destroyed with the template instance. Does a file scoped reactive variable get destroyed when the template is inactive?

File: apinf_packages/apis/client/import/import.js [hunk 4]
```diff
@@ -6,141 +6,100 @@ https://joinup.ec.europa.eu/community/eupl/og_page/european-union-public-licence
...
 
-  // code highlights for editor (JSON)
-  instance.editor.getSession().setMode('ace/mode/json');
+Template.importApiConfiguration.events({
+  'change #import-api': (event) => {
+    // File in input
+    const file = event.target.files[0];
+
+    // Check file extension
+    const acceptedExtensions = ['json', 'yml', 'yaml', 'txt'];
```
Comment (brylie) [inline apinf_packages/apis/client/import/import.js]: How do we parse files that use the `.txt` extension?

**Comment by marla-singer** [comment]
@Vellames What is the status of PR?

**Comment by Vellames** [comment]
@marla-singer i am sorry for the delay. I will finish today

File: apinf_packages/apis/client/import/import.js (hunk 4 above)
Comment (Vellames) [reply apinf_packages/apis/client/import/import.js]: If the file ends with txt i expect a yml. I think that remove .txt extension is the better solution

**Comment by Vellames** [comment]
> @Vellames Why did you decide to validate i18n?

As all parts of the application use i18n, then I thought the import should use too

> We don't really need to validate any i18n texts here. Just validating the import document with SimpleSchema.validate() should suffice.

Ok, so i will not use i18n here

File: apinf_packages/apis/client/import/import.js (hunk 2 above)
Comment (Vellames) [reply apinf_packages/apis/client/import/import.js]: Sorry, unnecessary code

File: apinf_packages/apis/client/import/import.js (hunk 3 above)
Comment (Vellames) [reply apinf_packages/apis/client/import/import.js]: I have not sure about this. I will move the variable to template instance

**Comment by Vellames** [comment]
@marla-singer , @brylie 
Where i should add a button to call this screen?

**Comment by marla-singer** [comment]
@Vellames The layout for your task places in the related issue https://github.com/apinf/platform/issues/2945#issuecomment-337243374

File: apinf_packages/apis/client/import/import.js [hunk 5]
```diff
@@ -6,144 +6,100 @@ https://joinup.ec.europa.eu/community/eupl/og_page/european-union-public-licence
...
 
 // Npm packages imports
 import jsyaml from 'js-yaml';
 
-Template.importApiConfiguration.onRendered(function () {
-  // keep current template instance
-  const instance = this;
+Template.importApiConfiguration.onCreated(() => {
+  // Create the apiConfiguration variable
+  Template.instance().data.apiConfiguration = new ReactiveVar();
```
Comment (marla-singer) [inline apinf_packages/apis/client/import/import.js]: Via `data` we take variables from the Parent template that are provided like

`{{> importApiConfiguration apiConfiguration=apiConfiguration }}`

And in this case, you can the value of variable `apiConfiguration` like `Template.instance().data.apiConfiguration`.

If you want to attach a variable to current template then you have to do `Template.instance().variableName`.

Re-make attaching

File: apinf_packages/apis/client/import/import.js [hunk 6]
```diff
@@ -6,144 +6,100 @@ https://joinup.ec.europa.eu/community/eupl/og_page/european-union-public-licence
...
+});
 
-  // initialises ace editor
-  instance.editor = ace.edit('editor');
+Template.importApiConfiguration.helpers({
+  // Get apiConfiguration value
+  apiConfiguration: () => {
+    return Template.instance().data.apiConfiguration.get();
```
Comment (marla-singer) [inline apinf_packages/apis/client/import/import.js]: The syle for helpers is 

```js
Template.templateName.helpers({
  helperName () {
  ...
 },
});
```

Re-make code style

File: apinf_packages/apis/client/import/import.js (hunk 4 above)
Comment (marla-singer) [reply apinf_packages/apis/client/import/import.js]: @Vellames yes, remove `.txt` extension

File: apinf_packages/apis/client/import/import.js [hunk 7]
```diff
@@ -6,144 +6,100 @@ https://joinup.ec.europa.eu/community/eupl/og_page/european-union-public-licence
...
-  instance.editor.setTheme('ace/theme/idle_fingers');
+Template.importApiConfiguration.events({
+  'change #import-api': (event, templateInstance) => {
+    // File in input
+    const file = event.target.files[0];
+
+    // Check file extension
+    const acceptedExtensions = ['json', 'yml', 'yaml', 'txt'];
+    const fileNameArray = file.name.split('.');
+    if (acceptedExtensions.indexOf(fileNameArray[fileNameArray.length - 1]) === -1) {
```
Comment (marla-singer) [inline apinf_packages/apis/client/import/import.js]: Forr checking extensions we have a special function for that
https://github.com/apinf/platform/blob/5dcd5459d6c16c084d8b59575d3cbd056000b84d/apinf_packages/core/helper_functions/file_name_ends_with.js#L11
Re-make checking extensions using the existed function

File: apinf_packages/apis/client/import/import.js (hunk 6 above)
Comment (Vellames) [reply apinf_packages/apis/client/import/import.js]: Ok

File: apinf_packages/apis/client/import/import.js (hunk 7 above)
Comment (Vellames) [reply apinf_packages/apis/client/import/import.js]: Ok

File: apinf_packages/apis/client/import/import.js (hunk 5 above)
Comment (Vellames) [reply apinf_packages/apis/client/import/import.js]: Sorry, i did not understand
I use ** api Configuration ** to show json in html, the variable has no relationship with another model.

**Comment by Vellames** [comment]
> @Vellames The layout for your task places in the related issue #2945 (comment)
#2945 done

**Comment by Vellames** [comment]
@marla-singer ready for review

**Comment by Vellames** [comment]
@marla-singer i will remove the `apis/import` route to solve #3053 . Please not review now

File: apinf_packages/apis/client/import/import.js (hunk 5 above)
Comment (marla-singer) [reply apinf_packages/apis/client/import/import.js]: Oookay

Instead of 
```js
Template.importApiConfiguration.onCreated(() => {
  // Create the apiConfiguration variable
   Template.instance().data.apiConfiguration = new ReactiveVar();
 });
```

Make
```js
Template.importApiConfiguration.onCreated(function () {
  const instnace = this;  
  // Initialize apiConfiguration variable
  instance.apiConfiguration = new ReactiveVar();
 });
```

File: apinf_packages/apis/client/import/import.js (hunk 6 above)
Comment (marla-singer) [reply apinf_packages/apis/client/import/import.js]: And here instead of
```js
  return Template.instance().data.apiConfiguration.get();
```
make
```js
  return Template.instance().apiConfiguration.get();
```

**Comment by Vellames** [comment]
@marla-singer done, ready for review

File: apinf_packages/apis/server/methods/config.js [hunk 8]
```diff
@@ -62,28 +21,51 @@ Meteor.methods({
...
+      // Validate the api
+      Apis.schema.validate(api);
 
+      // additional error handling
+      try {
+        // Check unique api name
+        const count = Apis.find({ name: jsonObj.name }).count();
+        if (count === 0) {
+          // Insert the API and get the id
+          const newApiBackend = Apis.insert(api);
```
Comment (marla-singer) [inline apinf_packages/apis/server/methods/config.js]: Change the variable name. The result is not `newApiBackend`. The result is `addedApiId` or `newApiId`

File: apinf_packages/apis/client/import/import.js [hunk 9]
```diff
@@ -6,144 +6,102 @@ https://joinup.ec.europa.eu/community/eupl/og_page/european-union-public-licence
...
-  // keep current template instance
-  const instance = this;
+// APInf imports
+import fileNameEndsWith from '/apinf_packages/core/helper_functions/file_name_ends_with';
 
-  // initialises ace editor
-  instance.editor = ace.edit('editor');
+Template.importApiConfiguration.onCreated(() => {
+  // Create the apiConfiguration variable
+  Template.instance().data.apiConfiguration = new ReactiveVar();
```
Comment (marla-singer) [inline apinf_packages/apis/client/import/import.js]: Re-make attaching.

Must be
```js
Template.instance().data.apiConfiguration = new ReactiveVar();
```
And below in code use
```js
Template.instance().apiConfiguration
``` and 
```js templateInstance.apiConfiguration```

File: apinf_packages/apis/client/add/add.html [hunk 10]
```diff
@@ -9,19 +9,32 @@
...
+            {{> afQuickField name='lifecycleStatus' id="api-lifecyclestatus" }}
+          </fieldset>
+          <button type="submit" class="btn btn-primary" id="submitapi-button">
+            {{_ 'addApi_button_text' }}
+          </button>
+        {{/ autoForm }}
+      </section>
+      <!-- separator -->
+      <div class="line-and-text">
+        <span>{{_ 'addApi_or' }}</span>
```
Comment (marla-singer) [inline apinf_packages/apis/client/add/add.html]: Change i18n tag name
Should be `addApi_sectionTitle_or` OR `addApi_separateLineTitle_or`

File: apinf_packages/apis/client/add/add.html [hunk 11]
```diff
@@ -9,19 +9,32 @@
...
+      </div>
+      <!-- Import API -->
+      <section>
+        <h2 class="second-title">{{_ "import_ApiConfiguration_Title" }}</h2>
```
[the remark this answers is not in the document]
Comment (marla-singer) [reply apinf_packages/apis/client/add/add.html]: Change i18n tag name
Should be `addApi_sectionTitle_importApiConfiguration`

**Comment by bajiat** [comment]
@marla-singer Will you have time to review this?

**Comment by marla-singer** [comment]
@bajiat I made the review 2 days ago and no changes since this time

**Comment by Vellames** [comment]
I will finish this weekend

File: apinf_packages/apis/client/add/add.html (hunk 10 above)
Comment (Vellames) [reply apinf_packages/apis/client/add/add.html]: Done

File: apinf_packages/apis/client/add/add.html (hunk 11 above)
[the remark this answers is not in the document]
Comment (Vellames) [reply apinf_packages/apis/client/add/add.html]: Done

File: apinf_packages/apis/client/import/import.html [hunk 12]
```diff
@@ -4,39 +4,19 @@
 https://joinup.ec.europa.eu/community/eupl/og_page/european-union-public-licence-eupl-v11 -->
 
 <template name="importApiConfiguration">
-  <form id="apiConfigurationUploadForm" class="form" method="post">
-
-    <legend>
-      {{_ "import_ApiConfiguration_Title" }}
```
[the remark this answers is not in the document]
Comment (Vellames) [reply apinf_packages/apis/client/import/import.html]: Ok

File: apinf_packages/apis/client/import/import.html [hunk 13]
```diff
@@ -4,39 +4,19 @@
...
-        <div class="btn-divider"></div>
-        <div class="form-group" style="text-align: right">
-          <button class="btn btn-success" type="submit">
-            {{_ "import_ApiConfiguration_Upload" }}
-          </button>
+  <div class="content-wrapper">
+    <form id="apiConfigurationUploadForm" class="form" method="post">
+      <div class="row">
+        <div class="col-xs-12">
+            <label for="import-api">{{_ "import_ApiConfiguration_FileLabel"}}</label>
```
[the remark this answers is not in the document]
Comment (Vellames) [reply apinf_packages/apis/client/import/import.html]: Ok

File: apinf_packages/apis/client/import/import.html [hunk 14]
```diff
@@ -4,39 +4,19 @@
...
+            <input type="file" id="import-api" class="form-control">
+            <span>{{_ "import_ApiConfiguration_Extensions" }}</span>
```
[the remark this answers is not in the document]
Comment (Vellames) [reply apinf_packages/apis/client/import/import.html]: Ok

File: apinf_packages/apis/client/import/import.html [hunk 15]
```diff
@@ -4,39 +4,19 @@
...
+        </div> 
+        <div class="col-xs-12 file-preview">
+          <pre>{{ apiConfiguration }}</pre>
+          <button class="btn btn-primary">{{_ "import_ApiConfiguration_ImportApi" }}</button>
```
[the remark this answers is not in the document]
Comment (Vellames) [reply apinf_packages/apis/client/import/import.html]: No problem, done

File: apinf_packages/apis/client/import/import.html [hunk 16]
```diff
@@ -4,39 +4,19 @@
...
         </div>
       </div>
-    </div>
-  </form>
-  <hr>
-</template>
+    </form>
+  </div> 
+</template>
```
[the remark this answers is not in the document]
Comment (Vellames) [reply apinf_packages/apis/client/import/import.html]: Done

File: apinf_packages/apis/client/import/import.js (hunk 9 above)
Comment (Vellames) [reply apinf_packages/apis/client/import/import.js]: I did not understand. If i make the attaching out of 'onCreated' event the 'Template.instance()' is null

File: apinf_packages/apis/client/import/import.js [hunk 17]
```diff
@@ -6,144 +6,102 @@ https://joinup.ec.europa.eu/community/eupl/og_page/european-union-public-licence
...
           // success message
           sAlert.success(status.message);
 
           // redirects to apiBackend view page
-          FlowRouter.go(`/api/${status.newBackendId}`);
+          FlowRouter.go(`/apis/${status.slug}`);
         } else {
           // error message
-          sAlert.error(status.message);
+          sAlert.error(status.message); // apiConfiguration.set('aaa');
```
[the remark this answers is not in the document]
Comment (Vellames) [reply apinf_packages/apis/client/import/import.js]: Sorry, removed :)

File: apinf_packages/apis/client/import/import.js (hunk 9 above)
Comment (marla-singer) [reply apinf_packages/apis/client/import/import.js]: Because of that `onCreated` and `onRendered` we don't use `Template.insatnce()`.

The right solution is:
```js
Template.importApiConfiguration.onCreated(function () {
  const instance = this;
  instance.apiConfiguration = new ReactiveVar();
});
```

File: apinf_packages/apis/server/methods/config.js (hunk 8 above)
Comment (Vellames) [reply apinf_packages/apis/server/methods/config.js]: Done

**Comment by saransh-dev** [comment]
I have a yaml file and I have uploaded it. But I got error "Name is required" because i got all things undefined.
```
{ 
	name: undefined,
	description: undefined,
	url: undefined,
	lifecycleStatus: undefined,
	managerIds: [ 'FJ29ry3wGAqKZFwDh' ] 
}
```

Here is yaml file:-

[swagger.yaml.zip](https://github.com/apinf/platform/files/1477702/swagger.yaml.zip)

**Comment by marla-singer** [comment]
@saransh-dev It doesn't suppose a swagger specification. When I wrote you in your PR about I meant to look at this realisation and "inspire" or take some cool feature or take the same library to uploading/parsing whatever. I don't mean that this import work this swagger specification

> "Another developer is working on the same task about add API via JSON file. Look at his PR, maybe you can find some useful idea"
