### PR TITLE
Fix translation, part 1

### LINKED ISSUE #2012: API catalog: Tooltip title "Avarage rating" doesn't have translation

### LINKED ISSUE #2014: API profile: SDK generate modal form doesn't have the translation
Verified on nightly.apinf.io
API profile -> Documantation tab -> SDK generate button
joxi_screenshot_1486124252582

### LINKED ISSUE #2016: API profile: Feedback form doesn't have the translation
1. API profile -> Feedback tab -> Send feedback button

joxi_screenshot_1486124408880

List from **Choose message type** should also have the translation

2. Feedback message type doesn't have the translation as well
joxi_screenshot_1486124622276

I'm not sure about the second point. Ping @bajiat

### LINKED ISSUE #2047: APIKA: Organization Profile: in Suomi language, the following elements need Finnish translation
_From @Nazarah on January 31, 2017 11:7_

1. API card add date
image

2. Edit organization button, Connect API to an Organization button and dialog
image

image

3. Filtering dropmenu
image

image

4. Contact pane in Organization Details editing dialog
image

_Copied from original issue: Digipalvelutehdas/APIKA#333_

### LINKED ISSUE #2048: APIKA: In Branding page, Social Media pane texts don't have Finnish translations
_From @Nazarah on January 31, 2017 7:17_

image

_Copied from original issue: Digipalvelutehdas/APIKA#327_

### PR DESCRIPTION
**Pull request by marla-singer**
Closes #2012 
Closes #2014 
Closes  #2016 
Closes #2048 
Closes #2047 (firstOption for form Connect API to organization)

### CODE REVIEW

**Comment by marla-singer** [comment]
@apinf/developers Ready for review

**Comment by marla-singer** [comment]
@apinf/developers Ready for review

File: settings/server/methods.js [hunk 1]
```diff
@@ -78,8 +78,8 @@ Meteor.methods({
     } catch (error) {
       // otherwise show an error
       const message = `Update gitHub configuration: ${error}`;
-
-      }
+      console.log(message);
```
Comment (brylie) [inline settings/server/methods.js]: Instead of `console.log`, we should throw an error. Something like: `return new Meteor.Error(message);`

File: settings/server/methods.js [hunk 2]
```diff
@@ -103,7 +103,7 @@ Meteor.methods({
       const message = `Update mail configuration: ${error}`;
 
       // Show an error message
-      
+      console.log(message);
```
Comment (brylie) [inline settings/server/methods.js]: Instead of `console.log`, we should throw an error. Something like: `return new Meteor.Error(message);`

File: settings/server/methods.js (hunk 1 above)
Comment (brylie) [inline settings/server/methods.js]: Reference: Meteor Methods [Error class](https://docs.meteor.com/api/methods.html#Meteor-Error)

File: settings/server/methods.js (hunk 2 above)
Comment (brylie) [inline settings/server/methods.js]: Reference: Meteor Methods [Error class](https://docs.meteor.com/api/methods.html#Meteor-Error)

**Comment by brylie** [comment]
Just a small improvement related to error handling. Rather than console.log, we should throw a Meteor.Error.

Reference: Meteor Methods [Error class](https://docs.meteor.com/api/methods.html#Meteor-Error)

File: settings/server/methods.js (hunk 1 above)
Comment (marla-singer) [inline settings/server/methods.js]: @brylie Actually, I don't know why `catch` block doesn't have any performances before. But after someone changes in `develop` branch, the Travis-CI  shows eslint errors although my branch even didn't have the specified problems.

**Comment by marla-singer** [comment]
@brylie Done
