### PR TITLE
Bugfix/allow methods

### LINKED ISSUE #2709: API Manager can't set the Try-out methods when Swagger file is uploaded as remote link
### Steps for reproduce:
1. Navigate to managed API
2. Open Documentation tab -> Click on Manage button
3. Specify URL to Swagger file
joxi_screenshot_1499081573534

4. Go to Swagger UI and look at endoints

### Expected
- Swagger UI has Try out buttons

### Founded
- A user can't call any request
joxi_screenshot_1499081687341
joxi_screenshot_1499081573534 3
joxi_screenshot_1499081573534 2
joxi_screenshot_1499081727159

### Suggestions:

1. Let API Manager controls Try-out methods even if file is filled as URL
or
2. Set all methods are allowed by default for file is filled as URL

### LINKED ISSUE #2888: Cannot read property 'otherUrl' of undefined
**Title**: 

Bowser console in anonym user case

**Steps to Reproduce**: 
1. Create an API
2. Sigh out
3. Open a browser console
4. Navigate to early created API
                    
**Actual result**:
errorin a browser console
```
Exception in template helper: TypeError: Cannot read property 'otherUrl' of undefined
  at Object.displayLinkBlock (https://nightly.apinf.io/454c1e17eab22e0ed2d3852760ba9051d3b75a8e.js?meteor_js_resource=true:411:24741)
    ...
```
         
**Expected Behavior**:
No errors
                   
**Environment**:
staging.apinf.io 0.49.0
Chrome browsers

anonym-user-case

### PR DESCRIPTION
**Pull request by marla-singer**
Closes #2888 
Closes #2709

### CODE REVIEW

File: apinf_packages/api_docs/client/view/documentation.js [hunk 1]
```diff
@@ -87,7 +87,7 @@ Template.apiDocumentation.helpers({
     const apiDoc = this.apiDoc;
 
     // Display block if a user is manager of current API or URL is set
-    return api.currentUserCanManage() || apiDoc.otherUrl;
+    return api.currentUserCanManage() || (apiDoc && apiDoc.otherUrl);
```
Comment (brylie) [inline apinf_packages/api_docs/client/view/documentation.js]: Add whitespace inside of parenthesis:

```
( blah )
```

Comment (marla-singer) [reply apinf_packages/api_docs/client/view/documentation.js]: ESlint says you're wrong
joxi_screenshot_1504790719415
