### PR TITLE
fixed issue [ API Profile ] After updating value of API it redirects to API catalog #3139

### LINKED ISSUE #3139: [ API Profile ] After updating value of API it redirects to API catalog
### Steps
1. Create an API or go to existing API
2. Navigate to Settings tab
3. Change Lifecycle status, description or URL value (but not Name parameter)
4. Click on the button "Save"

### Expected result
- API profile information is updated and the API Profile page is still open
- No errors

### Actual result
- Error on the server side
```
Exception from sub apiComposite id PkGJF89NkXef6kiLa Error: Match error: Expected string, got null
  at exports.check (packages/check.js:55:15)
  at [object Object].<anonymous> (apinf_packages/apis/collection/server/publications.js:57:3)
```
- Redirect to API Catalog

### PR DESCRIPTION
**Pull request by saransh-dev**
Closes #3139 

## Changes
- Removed `else` from `apis/profile/settings/details/`.

## Developer checklist
This checklist is to be completed by the PR developer:

- [ ] Alternative solutions were compared/discussed before writing code
    - [ ] trade-offs with this solution are considered acceptable
- [ ] Code in this PR adheres to the [project styleguide](CONTRIBUTING.md)
- [ ] This pull request does not decrease project test coverage
- [ ] If the code changes existing database collection(s), migration has been written
- [ ] If UI texts are added or changed, all texts are internationalized

## Reviewer checklist
Reviewed by: @marla-singer 

This list is to be completed by the pull request reviewer:
- [ ] Code works as described/expected
- [ ] Code seems to be error free
    - [ ] no browser console errors visible
    - [ ] no server console errors visible
    - [ ] passes CI build
- [ ] Code is written in a way that promotes maintainability
    - [ ] easy to understand
    - [ ] well organized
    - [ ] follows project coding standards and conventions
    - [ ] well documented

### CODE REVIEW

File: apinf_packages/apis/client/profile/settings/details/autoform.js [hunk 1]
```diff
@@ -14,15 +14,10 @@ AutoForm.hooks({
...
-      if (slug) {
       // Redirect to updated API with new slug.
       // It is use while api's name will update slug have to change
       // that's mean routing change
-        FlowRouter.go('viewApi', { slug });
-      } else {
-        // Otherwise Redirect to API Catalog
-        FlowRouter.go('apiCatalog');
-      }
+      FlowRouter.go('viewApi', { slug });
```
Comment (marla-singer) [inline apinf_packages/apis/client/profile/settings/details/autoform.js]: Bad decision. As you wrote in the issue:
> As i found the issue, this.updateDoc.$set.slug; gets undefine when we upate api except api name inside autoform file 

1. Get `slug` from `updateDoc` variable
2. If slug exists then the slug is updated  and then redirects to new slug
3. otherwise no ant redirect

File: apinf_packages/apis/client/profile/view.js [hunk 2]
```diff
@@ -30,8 +30,10 @@ Template.viewApi.onCreated(function () {
...
     // Take slug from params
     const slug = FlowRouter.getParam('slug');
-    // Subscribe to API and related organization
-    templateInstance.subscribe('apiComposite', slug);
+    if (slug) {
+      // Subscribe to API and related organization
+      templateInstance.subscribe('apiComposite', slug);
+    }
     // Subscribe to public proxy details
     templateInstance.subscribe('proxyCount');
```
Comment (marla-singer) [inline apinf_packages/apis/client/profile/view.js]: Move subscription functions "proxyCount" and "publicProxyDetails" away from autorun and you will have the next structure in the onCreated part:

1. subscribe to proxyCount
2. subscribe to publicProxyDetails
3. autorun function:
- get `slug` parameter
- make sure it that exists
- then subscribe to apiComposite
- then get API
- make sure APi exists
- then save it in templateInstance
- then get branding and etc

**Comment by marla-singer** [comment]
@saransh-dev What status of this PR?

**Comment by saransh-dev** [comment]
Hi @marla-singer, Currenlty I am working on APInf-Harvester, and i need to delivered it on tomorrow morning. After that I will work on your suggestion.

**Comment by marla-singer** [comment]
@saransh-dev Good, take your time. Just ask the status 👍

File: apinf_packages/apis/client/profile/settings/details/autoform.js [hunk 3]
```diff
@@ -13,16 +13,11 @@ AutoForm.hooks({
   apiDetailsForm: {
     onSuccess () {
       // Getting new slug from this.udateDoc
-      const slug = this.updateDoc.$set.slug;
-      if (slug) {
+      const updateDoc = this.updateDoc.$set.slug;
```
Comment (marla-singer) [inline apinf_packages/apis/client/profile/settings/details/autoform.js]: Incorrect variable name. 
You fetch value of **slug** field. It is not **updateDoc**

Comment (marla-singer) [reply apinf_packages/apis/client/profile/settings/details/autoform.js]: Again it doesn't work as expected. We need easier solution as we have
