### PR TITLE
Use single method to form slug

### LINKED ISSUE #3389: Changes into functions, which add slug either in API or in Organization
## Problem
In program code there are several places, where a slug is needed to be formed and added into API or Organization
- UI
  - add API/Organization
  - modify API/Organization
- Migration
- Management API (here slug functionality is missing)
  - POST /apis or /organizations
  - PUT /apis or /organizations

Currently there are two functions, where operations are done:
- updateOrganizationBySlug
- updateApiBySlug

In both cases functionality is following:
- at first it is checked, if API/Org exists
- then slug is formed and slug uniqueness is checked
- last new slug is written into db (API/Org)

However, the similar operation flow is not optimal for each case.

- For migration it is OK, add the slug, if it was missing.
- for operation from UI or via Management API it is not optimal, because it leads to several DB writes. Especially complicated it is in case of operation via Management API, when all operations must succeed or fail and a rollback functionality is needed in case some operation succeeds and another fails.

In Management API using these functions cause several DB writes for same document.

### Solution
Extract this into own function:
- then slug is formed and slug uniqueness is checked

That way the slug forming can be called separately and only one DB write is needed, when all changes and the change of slug can be written at one time into DB document.

### PR DESCRIPTION
**Pull request by deligence-dharmendra**
Closes #3389

## Changes

- remove unnecessary code
- add a single method "formSlugFromName" to from slug
- changes in home server method
- removed method formSlugFromOrganizationsName, formSlugFromApiName

## Developer checklist
This checklist is to be completed by the PR developer:

- [ ] Alternative solutions were compared/discussed before writing code
    - [ ] trade-offs with this solution are considered acceptable
- [ ] Code in this PR adheres to the [project styleguide](CONTRIBUTING.md)
- [ ] This pull request does not decrease project test coverage
- [ ] If the code changes existing database collection(s), migration has been written
- [ ] If UI texts are added or changed, all texts are internationalized

## Reviewer checklist
Reviewed by: @matleppa 

This list is to be completed by the pull request reviewer:
- [ ] Code works as described/expected
- [ ] Code seems to be error free
    - [ ] no browser console errors visible
    - [ ] no server console errors visible
    - [ ] passes CI build
- [ ] Code is written in a way that promotes maintainability
    - [ ] easy to understand
    - [ ] well organized
    - [ ] follows project coding standards and conventions
    - [ ] well documented

### CODE REVIEW

**Comment by deligence-dharmendra** [comment]
@matleppa, @marla-singer,  I have tried to make a single method to the formation of slug in all cases(migration, UI, and management), I have placed new method "formSlugFromName" in home/server/method file because APIs and Organization already used in it.
Please advise

File: apinf_packages/apis/server/api.js [hunk 1]
```diff
@@ -709,9 +716,9 @@ CatalogV1.addCollection(Apis, {
         // If API name given
         if (bodyParams.name) {
```
Comment (matleppa) [inline apinf_packages/apis/server/api.js]: Move this slug functionality to be done earlier, after line 598, where it is checked, if parameter "name" was given. 
And if forming of slug fails, response with error message, same way as in POST method.

File: apinf_packages/organizations/server/api.js [hunk 2]
```diff
@@ -325,11 +325,17 @@ ManagementV1.addRoute('organizations', {
...
       // Get Formed slug
-      const slugData = Meteor.call('formSlugFromOrganizationsName', bodyParams.name);
-      // Include slug
-      organizationData.slug = slugData.slug;
-      // Include friendlySlugs
-      organizationData.friendlySlugs = slugData.friendlySlugs;
+      const slugData = Meteor.call('formSlugFromName', 'Organizations', bodyParams.name);
+
+      // If formed slug true
+      if (slugData && typeof slugData === 'object') {
```
Comment (matleppa) [inline apinf_packages/organizations/server/api.js]: Same correction as in API slug POST method. 
Failure in forming slug is considered as failure related parameter "name" thus response with error message.

    return errorMessagePayload(500, 'Forming slug for Organization failed.');

File: apinf_packages/organizations/server/api.js [hunk 3]
```diff
@@ -622,9 +628,9 @@ ManagementV1.addRoute('organizations/:id', {
       // If Organization name given
       if (bodyParams.name) {
```
Comment (matleppa) [inline apinf_packages/organizations/server/api.js]: Same correction as in API PUT method.
Move slug forming to be done within parameter "name" checking. In case slug forming fails, respond with error message.
