### PR TITLE
RegEx messages

### LINKED ISSUE #2160: If a regular expression fails, inform user about the reason
Currently, if regular expression fails, user gets a message aboutit failing, but no information about what was wrong with the string they have typed. Hence, it is difficult for the user to fix this.

# Options:
* Include the rule for the regular expression (e.g. allowed characters)
* Show the exact error (e.g. dot is not allowed)

### PR DESCRIPTION
**Pull request by nnn**
Closes #2160

### CODE REVIEW

File: core/lib/simple_schema_config.js [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+SimpleSchema.messages({
+  regEx: [
+    // TODO: define custom mesages for every RegEx
+    { exp: SimpleSchema.RegEx.Url, msg: '[label] must be a valid URL' },
+    { exp: SimpleSchema.RegEx.Id, msg: '[label] must be a valid alphanumeric ID' },
+    { exp: SimpleSchema.RegEx.Domain, msg: '[label] must be a valid domain' },
+    { exp: SimpleSchema.RegEx.Email, msg: '[label] must be a valid e-mail address' },
+    { exp: proxyBasePathRegEx, msg: '[label] allowed characters: A-Z' },
+    { exp: apiBasePathRegEx, msg: '[label] allowed characters: A-Z' },
+    { exp: contactPhone, msg: '[label] allowed characters: A-Z' },
```
Comment (brylie) [inline core/lib/simple_schema_config.js]: This does not correspond with the `contactPhone` regex.

**Comment by brylie** [comment]
I see this is a work-in-progress, so I will wait till it is closer for comments. It is looking good for a work-in-progress, though.

File: organizations/collection/regex.js [hunk 2]
```diff
@@ -0,0 +1,3 @@
+// all numbers (0-9) , + , - , space ,/ are allowed and can appear anywhere in the phone numbers
+// e.g. 754-3010,(541) 754-3010,1-541-754-3010,1-541-754-3010,191 541 754 3010,(089) / 636-48018
+export const contactPhone = new RegExp(/^[0-9-+()/\s.]+$/);
```
Comment (marla-singer) [inline organizations/collection/regex.js]: Use `export default`

Comment (nnn) [inline organizations/collection/regex.js]: Using `export default` as  
```
const contactPhone = new RegExp(/^[0-9-+()/\s.]+$/);
export default contactPhone
```
gives me:

```
Error: Invalid definition for contact.phone field.
W20170313-13:04:17.232(2)? (STDERR)     at packages/aldeed_simple-schema.js:1429:13
W20170313-13:04:17.233(2)? (STDERR)     at Function._.each._.forEach (packages/underscore.js:147:22)
W20170313-13:04:17.233(2)? (STDERR)     at [object Object].SimpleSchema (packages/aldeed_simple-schema.js:1426:5)
W20170313-13:04:17.234(2)? (STDERR)     at meteorInstall.organizations.collection.schema.js (organizations/collection/schema.js:12:24)
W20170313-13:04:17.234(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
W20170313-13:04:17.235(2)? (STDERR)     at require (packages/modules-runtime.js:120:16)
```

Comment (marla-singer) [inline organizations/collection/regex.js]: Of course, it gave. 
```javascript
import contactPhone from '/path-to-library/';
```

Comment (nnn) [inline organizations/collection/regex.js]: Oh, thanks. Missed that.

**Comment by nnn** [comment]
@apinf/developers can anybody help me with these regExs:
```
RegExp(/^\/[\w\-/\.:\?#@!\$&\*\+,;=\'\(\)]+\/$/);
RegExp(/^\/[\w\-/\.:\?#@!\$&\*\+,;=\'\(\)]*$/);
```
What are allowed characters here?

**Comment by brylie** [comment]
> @apinf/developers can anybody help me with these regExs:

Where are those located in our code?

**Comment by brylie** [comment]
> @apinf/developers can anybody help me with these regExs:
>
>```
>RegExp(/^\/[\w\-/\.:\?#@!\$&\*\+,;=\'\(\)]+\/$/);
>RegExp(/^\/[\w\-/\.:\?#@!\$&\*\+,;=\'\(\)]*$/);
>```

Basically, anything with a `\` in front of it. 

@matleppa could you add a comment before those lines of code, to explain them in plain English?

**Comment by shaliko** [comment]
@brylie May be will be useful http://scriptular.com/

**Comment by brylie** [comment]
@shaliko thanks for the link. It seems like @nnn is wanting more of an explanation for what the regex does, as opposed to 'feeling around' to see what patterns it matches. To this end, [Regex101](https://regex101.com/) has an **explanation** tab that describes what a given regex is doing:

screenshot_20170313_134540

**Comment by matleppa** [comment]
[\w\-/\.:\?#@!\$&\*\+,;=\'\(\)]
The characters indicated inside the square brackets are allowed followingly (sets are here separated with |):
 \w allows:  a-zA-Z0-9_ | following characters are allowed as such: /:#@!&,;= | following characters are allowed (but they must here be escaped with \ ): \- \. \? \$ \* \+ \' \( \) so allowed characters are following: -.?$*+'()

**Comment by nnn** [comment]
Open for suggestion on[ i18n token names](https://github.com/apinf/platform/pull/2276/commits/9389d8f2d9f24126dc0a34b73d56b334d0b18954#diff-e5b840a8188cf895eb7bd76a8073cea7R375) and messages text.

File: core/lib/simple_schema_config.js [hunk 3]
```diff
@@ -12,8 +12,8 @@ SimpleSchema.messages({
     { exp: SimpleSchema.RegEx.Id, msg: '[label] must be a valid alphanumeric ID' },
     { exp: SimpleSchema.RegEx.Domain, msg: '[label] must be a valid domain' },
     { exp: SimpleSchema.RegEx.Email, msg: '[label] must be a valid e-mail address' },
-    { exp: proxyBasePathRegEx, msg: 'Allowed characters for [label]: A-Z' },
-    { exp: apiBasePathRegEx, msg: 'Allowed characters for [label]: A-Z' },
+    { exp: proxyBasePathRegEx, msg: '[label] must begin and end with "/"' },
```
Comment (brylie) [inline core/lib/simple_schema_config.js]: I can't recall if it is difficult/impossible to internationalize these regex validation messages. Since they are defined in a common folder, rather than a `client` folder, we may have encountered difficulties in the past.

**Comment by brylie** [comment]
@matleppa would you like to finish this PR review?

**Comment by matleppa** [comment]
Allowed alphanumeric characters and-.?$*+'()

There should also be mentioned underscore _
Also there should be a space between (and-  -->  and -)

**Comment by matleppa** [comment]
The end of my earlier comment was misleading.
All those mentioned characters are allowed, I just presented in three groups.
 
-.?$*+'()/:#@!&,;=

**Comment by nnn** [comment]
@matleppa done

**Comment by brylie** [comment]
@matleppa it does not appear that this PR included code comments for the `baseUrl` regular expression. Please remember to add those comments, as they would clearly be helpful.
