### PR TITLE
Removed maximum length restrictions when changing password

### LINKED ISSUE #2771: Password length limited when changing password
**Steps to Reproduce**: 
1. go to page: https://nightly.apinf.io/settings/account
2. try to enter password over 20 characters
                    
**Outcome**:
"New Password" and "Confirm new Password" do not allow passwords above 20 characters.
         
**Expected Behavior**:
Password fields should not limit the length of the password. Changing passwords should also be consistent with registration, so if there are any limits, they should be the same in registration and password change.

**Environment**:
Ubuntu GNOME 17.04, Firefox Developer Edition 55.0b10, APInf Nightly (https://nightly.apinf.io)

### PR DESCRIPTION
**Pull request by matleppa**
Closes #2771

### CODE REVIEW

File: apinf_packages/users/client/account/password/schema.js [hunk 1]
```diff
@@ -9,17 +9,17 @@ import { SimpleSchema } from 'meteor/aldeed:simple-schema';
 const updatePasswordSchema = new SimpleSchema({
   old: {
     type: String,
-    max: 50,
+    // max: 50,
```
Comment (brylie) [inline apinf_packages/users/client/account/password/schema.js]: Remove commented code.

File: apinf_packages/users/client/account/password/schema.js [hunk 2]
```diff
@@ -9,17 +9,17 @@ import { SimpleSchema } from 'meteor/aldeed:simple-schema';
...
   },
   new: {
     type: String,
     min: 6,
-    max: 20,
+    // max: 50,
```
Comment (brylie) [inline apinf_packages/users/client/account/password/schema.js]: Remove commented code.

File: apinf_packages/users/client/account/password/schema.js [hunk 3]
```diff
@@ -9,17 +9,17 @@ import { SimpleSchema } from 'meteor/aldeed:simple-schema';
...
   },
   confirm: {
     type: String,
     min: 6,
-    max: 20,
+    // max: 50,
```
Comment (brylie) [inline apinf_packages/users/client/account/password/schema.js]: Remove commented code.
