### PR TITLE
Fixed Make the alert when new password and confirm new password dont …

### LINKED ISSUE #3210: Make the alert text more intuitive when new password and confirm new password don't match
**Steps to Reproduce**: 
1. Login to https://nightly.apinf.io
2. Go to User>Accounts
3. input current password
4. input "new password": testing123
5. input "confirm new password": testing369

**Outcome**:
According to testcase, an alert message "Passwords do not match" is supposed to appear below "confirm new password" field.
However, the current message is "Unknown validation error".
This is more confusing to the user and doesn't really give the exact reason for failure in password change
image

         
**Expected Behavior**:
Change the alert text to "Passwords do not match" to make it sound more intuitive
                   
**Environment**:
Windows 10, Chrome browser (latest), Nightly APInf

### PR DESCRIPTION
**Pull request by deligence-dharmendra**
…match

Closes #3210

## Changes

- changes in schema file
- changes in password autoform

## Developer checklist
This checklist is to be completed by the PR developer:

- [ ] Alternative solutions were compared/discussed before writing code
    - [ ] trade-offs with this solution are considered acceptable
- [ ] Code in this PR adheres to the [project styleguide](CONTRIBUTING.md)
- [ ] This pull request does not decrease project test coverage
- [ ] If the code changes existing database collection(s), migration has been written
- [ ] If UI texts are added or changed, all texts are internationalized

## Reviewer checklist
Reviewed by: @marla-singer @matleppa 

This list is to be completed by the pull request reviewer:
- [ ] Code works as described/expected
- [ ] Code seems to be error free
    - [ ] no browser console errors visible
    - [ ] no server console errors visible
    - [ ] passes CI build
- [ ] Code is written in a way that promotes maintainability
    - [ ] easy to understand
    - [ ] well organized
    - [ ] follows project coding standards and conventions
    - [ ] well documented

### CODE REVIEW

File: apinf_packages/users/client/account/password/autoform.js [hunk 1]
```diff
@@ -17,9 +17,15 @@ AutoForm.hooks({
       Accounts.changePassword(insertDoc.old, insertDoc.new, (error) => {
         $('.btn-primary').attr('disabled', null);
         if (error) {
+          let message = '';
+          if (error.error === 403) {
```
Comment (marla-singer) [inline apinf_packages/users/client/account/password/autoform.js]: Why do we need this checking?

Comment (marla-singer) [reply apinf_packages/users/client/account/password/autoform.js]: I checked and it is still working with the previous code.

**remove your changes from this file**
