### PR TITLE
Contact form

### LINKED ISSUE #1525: Feedback form not working properly
When submitting the Feedback form, the page is reloaded instead of properly submitting. In addition, rendering the Feedback form produces several console errors.

### LINKED ISSUE #1572: Contact form not working
The contact form code does not correctly use our send mail settings. Update the contact form code to get the correct settings from our Settings collection.

### PR DESCRIPTION
**Pull request by frenchbread**
Closes #1572, #884

### CODE REVIEW

**Comment by frenchbread** [comment]
Partly fixed, mail settings fetch refactored. Yet, the contact form data is not delivered via email..

**Comment by frenchbread** [comment]
Autoform is already used for the contact form.

**Comment by brylie** [comment]
@frenchbread note that this is related to the API Feedback form, rather than the Home page contact form.

The API Feedback form is not submitting correctly.

File: home/server/methods.js [hunk 1]
```diff
@@ -13,9 +14,12 @@ Meteor.methods({
 
     this.unblock();
 
+    // Get email settings
+    const mailSettings = Settings.findOne().mail;
```
Comment (brylie) [inline home/server/methods.js]: This is dangerous code. `Settings.findOne()` may return undefined, or the `.mail` attribute may be undefined.

When you use `mailSettings.toEmail` later, it may throw an error if either of the above cases were true.

**Comment by frenchbread** [comment]
> note that this is related to the API Feedback form, rather than the Home page contact form.

@brylie Right, my bad. Closing this `branch`

**Comment by brylie** [comment]
@frenchbread it is OK, and the changes are actually helpful.

Please open an issue related to the 'contact form' and open a PR with this branch.

**Comment by brylie** [comment]
I updated the PR description with a new task related to this fix.

@frenchbread please verify whether issue #884 is also fixed by this PR.

**Comment by frenchbread** [comment]
@brylie Verified. Please review

**Comment by brylie** [comment]
@frenchbread I am merging this now.

Note that we need to add `Closes #` on a new line for *each* issue that a PR closes in order for the issue to be properly linked. You can use alternative keywords like 'fixes', etc., but they have to be on a new line for each linked issue.
