### PR TITLE
Fixed: Clicking buttons [Make all feedback public/private] causes exceptions

### LINKED ISSUE #2966: Clicking buttons [Make all feedback public/private] causes exceptions
### Description ###
1. Create an API
2. Open API
3. Open Feedback tab
4. Press button [Make all feedback public] or [Make all feedback private]

### Result ###
Console log shows: 
Error invoking Method 'changeAllFeedbacksVisibility': Match failed [400]

In command prompt can be seen exception:
I20170922-13:54:36.273(3)? Exception while invoking method 'changeAllFeedbacksVisibility' Error: Match error: Expected boolean, got null
I20170922-13:54:36.276(3)?     at exports.check (packages\check.js:55:15)
I20170922-13:54:36.278(3)?     at [object Object].Meteor.methods.changeAllFeedbacksVisibility (apinf_packages/feedback/server/methods.js:22:5)
I20170922-13:54:36.279(3)?     at [object Object].methodMap.(anonymous function) (apinf_packages/core/capture_exception/server/wrap_meteor_methods.js:17:30)
I20170922-13:54:36.281(3)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
I20170922-13:54:36.282(3)?     at packages/ddp-server/livedata_server.js:719:19
I20170922-13:54:36.286(3)?     at [object Object].EVp.withValue (packages\meteor.js:1135:15)
I20170922-13:54:36.291(3)?     at packages/ddp-server/livedata_server.js:717:46
I20170922-13:54:36.295(3)?     at [object Object].EVp.withValue (packages\meteor.js:1135:15)
I20170922-13:54:36.305(3)?     at packages/ddp-server/livedata_server.js:715:46
I20170922-13:54:36.306(3)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp-server/livedata_server.js:689:23)
I20170922-13:54:36.308(3)?     at packages/ddp-server/livedata_server.js:559:43
I20170922-13:54:36.317(3)? Sanitized and reported to the client as: Match failed [400]

### Expected result ###
No exceptions.

### PR DESCRIPTION
**Pull request by Vellames**
Closes #2966 

The buttons are working normally now

### CODE REVIEW

**Comment by Vellames** [comment]
@matleppa Ready for review

File: apinf_packages/feedback/client/change_visibility/change_visibility.js [hunk 1]
```diff
@@ -13,11 +13,14 @@ import { Modal } from 'meteor/peppelg:bootstrap-3-modal';
 
 Template.changeFeedbackVisibility.events({
   'click #confirm-change-visibility': () => {
+    // Get template instance
+    const instance = Template.instance();
```
Comment (marla-singer) [inline apinf_packages/feedback/client/change_visibility/change_visibility.js]: The event handler has two parameters: event and templateInstance.
```js
'click #confirm': (event, templateInstance) => {...}
```
Use the second parameter to get data from template instead of `Template.instance()`

**Comment by Vellames** [comment]
@marla-singer Done
