### PR TITLE
1st time hex codes for branding colors dont appear

### LINKED ISSUE #3212: On navigating the branding page for the 1st time, hex codes for branding colors (primary, peimary text and covoerphoto overlay) don't appear
**Steps to Reproduce**: 
1. login to staging.apinf.io as admin (if possible in a fresh deployment, when site has default colors set)
2. go to user>Branding page
3. Check fields under Colors section         
          
**Outcome**:
The colors section shows no hex values for primary, primary text and cover photo overlay fields.
The values appear as soon as the primary colors are changes with customized color .
image

**Expected Behavior**:
Even if default values for the fields are set, the hex value should appear in relevant field.
                   
**Environment**:

Windows 10, Chrome browser (latest), APInf staging (https://stanging.apinf.io)

### PR DESCRIPTION
**Pull request by deligence-dharmendra**
Closes #3212

## Changes
Describe your changes here as a bulleted list:
- create new branding migration file
- changes in custom style sheet js file

## Developer checklist
This checklist is to be completed by the PR developer:

- [ ] Alternative solutions were compared/discussed before writing code
    - [ ] trade-offs with this solution are considered acceptable
- [ ] Code in this PR adheres to the [project styleguide](CONTRIBUTING.md)
- [ ] This pull request does not decrease project test coverage
- [ ] If the code changes existing database collection(s), migration has been written
- [ ] If UI texts are added or changed, all texts are internationalized

## Reviewer checklist
Reviewed by: @marla-singer @matleppa 

This list is to be completed by the pull request reviewer:
- [ ] Code works as described/expected
- [ ] Code seems to be error free
    - [ ] no browser console errors visible
    - [ ] no server console errors visible
    - [ ] passes CI build
- [ ] Code is written in a way that promotes maintainability
    - [ ] easy to understand
    - [ ] well organized
    - [ ] follows project coding standards and conventions
    - [ ] well documented

### CODE REVIEW

**Comment by marla-singer** [comment]
@deligence-dharmendra I suggest another way to resolve
1. Add the default value directly in Branding schema collection
2. Write a new migration step that will update database data

**Comment by Nazarah** [comment]
@krashna-deligence 
Just checked the latest changes made into the branch in my localhost.
It has the following issue:
Primary text shows the color in plain text (e.g. 'white')
Cover photo overlay doesn't show any hex value at all.
All the color pickers should show hex value.
brandingcolor

**Comment by deligence-dharmendra** [comment]
Hi @Nazarah ,
I'm working on this issue. Can you suggest me default value for all color field, script takes this value from the custom stylesheet.  See below
``primaryColorText = 'white';
coverPhotoOverlay = '';
overlayTransparency = 0;
primaryColor = '#2fa4e7';``

Please advise

**Comment by Nazarah** [comment]
@krashna-deligence 
#2fa4e7 - primary 
#ffffff - primary text
#ffffff - cover photo overlay

File: apinf_packages/core/migrations/server/13-add-color-for-branding.js [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+  up () {
+    const branding = Branding.findOne();
+    // Make sure Branding configuration exists
+    if (branding) {
+      // Create blank object
+      let data = {};
+      // Make sure branding colors exists
+      if (branding.colors) {
+        // Colors data object
+        data = {
```
Comment (marla-singer) [inline apinf_packages/core/migrations/server/13-add-color-for-branding.js]: You have the repeated code. You have to make a general element that is used in several cases. What I mean

1. Create a color schema that contains the existed values or default
2. If Branding config exists then update that otherwise create a new with defined color schema

Comment (marla-singer) [reply apinf_packages/core/migrations/server/13-add-color-for-branding.js]: In JS there has 
```js
const colorSchema = branding.color || {};
```
if `branding.color` is defined then `colorSchema` will have value of that otherwise wil have `{}`

Comment (marla-singer) [reply apinf_packages/core/migrations/server/13-add-color-for-branding.js]: Use it to avoid double difinition of `data` variable

File: apinf_packages/core/migrations/server/13-add-color-for-branding.js [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+          primary: branding.colors.primary || '#2fa4e7',
+          primaryText: branding.colors.primaryText || '#ffffff',
+          coverPhotoOverlay: branding.colors.coverPhotoOverlay || '#ffffff',
+          overlayTransparency: branding.colors.overlayTransparency || 0,
+        };
+      } else {
+        // Colors data object
+        data = {
+          primary: '#2fa4e7',
```
Comment (marla-singer) [inline apinf_packages/core/migrations/server/13-add-color-for-branding.js]: What about default values.  Get it from Branding collection schema directly

**Comment by marla-singer** [comment]
**Tested cases**
- [x] 1. Branding didn't exist
- [x] 2. Branding existed w/out colors
- [x] 2. Branding existed w/ some colors
- [x] 2. Branding existed w/ full colors

The last change is squash all commits to one and let's merge it
