### PR TITLE
Feature/fix swagger codegen

### LINKED ISSUE #2487: Generate SDK file displays error
# Steps  
1.Visit https://staging.apinf.io v 0.43.0 
2.Login 
3.Add API and connect it to proxy  (eg. staging/API-umbrella New)
4.Go to above added API   
5.Click on 'Documentation' tab 
6.Upload documentation file (eg.swagger.yaml)  
7.Go to 'SDK Generate'  
8.Select any language 
9.Click on 'Download'  

# Findings 
- API documentation view shows  a 'warning' message  
- Generate SDK file shows error "File not supported by Code Generator....."     

# Screenshot 
upload_documentation_file_info_warning       

generate_sdk_file_error_msg1

### PR DESCRIPTION
**Pull request by brylie**
Closes #2487 

# Changes
- hard code list of language options
  - we were maintaining a semi-hard-coded list anyway, so why not simplify?
- simplify template markup
- simplify autoform logic

### CODE REVIEW

**Comment by brylie** [comment]
The code has been refactored to work, but there is still a basic error coming back from Swagger CodeGen:

```js
failed [400] 
{
  "code": 1,
  "type": "error",
  "message": "The swagger specification supplied was not valid"
}
```

I can get a successful response with the following cURL command:

```bash
curl -X POST -H "content-type:application/json" -d '{"swaggerUrl":"http://petstore.swagger.io/v2/swagger.json"}' http://generator.swagger.io/api/gen/clients/ruby
```

**Comment by bajiat** [comment]
@marla-singer Could you mentor @brylie?

**Comment by marla-singer** [comment]
@bajiat Sure

**Comment by marla-singer** [comment]
@brylie ESlint erros

**Comment by bajiat** [comment]
@mauriciovieira Could you review this PR? it's ready for review.

File: api_docs/client/codegenerator/codeGeneratorLanguageOptions.js [hunk 1]
```diff
@@ -0,0 +1,162 @@
+/* Copyright 2017 Apinf Oy
```
Comment (mauriciovieira) [inline api_docs/client/codegenerator/codeGeneratorLanguageOptions.js]: Shouldn't this file be named code_generator_language_options.js according to our [coding standards](https://github.com/apinf/platform/blob/develop/CONTRIBUTING.md#file-names)?

File: api_docs/client/swaggerUI/swaggerUi.js [hunk 2]
```diff
@@ -14,7 +14,7 @@ Template.swaggerUi.onCreated(() => {
   instance.dataFetched = new ReactiveVar(false);
```
Comment (mauriciovieira) [inline api_docs/client/swaggerUI/swaggerUi.js]: Shouldn't this file be renamed to `api_docs/client/swagger_ui/swagger_ui.js` according to our [coding standards](https://github.com/apinf/platform/blob/develop/CONTRIBUTING.md#file-names)?

File: api_docs/client/swaggerUI/swaggerUiContent/swaggerUiContent.js [hunk 3]
```diff
@@ -11,7 +11,7 @@ Template.swaggerUiContent.onRendered(function () {
 
   /* eslint-disable */
```
Comment (mauriciovieira) [inline api_docs/client/swaggerUI/swaggerUiContent/swaggerUiContent.js]: What rules are we exactly disabling here? Shouldn't it be better to fix the rules?

File: api_docs/client/swaggerUI/swaggerUiContent/swaggerUiContent.js [hunk 4]
```diff
@@ -11,7 +11,7 @@ Template.swaggerUiContent.onRendered(function () {
```
Comment (mauriciovieira) [inline api_docs/client/swaggerUI/swaggerUiContent/swaggerUiContent.js]: Shouldn't this file be renamed to `api_docs/client/swagger_ui/swagger_ui_content/swagger_ui_content.js` according to our [coding standards](https://github.com/apinf/platform/blob/develop/CONTRIBUTING.md#file-names)?

File: branding/logo/client/upload/resumable.js [hunk 5]
```diff
@@ -23,10 +23,10 @@ Meteor.startup(() => {
...
       filename: file.fileName,
       contentType: file.file.type,
-    }, (err) => {
-      if (err) {
-        console.warn('File creation failed!', err);
-        return;
+    }, (error) => {
+      if (error) {
+        // Handle error condition
+        throw new Meteor.Error('File creation failed!', error);
```
Comment (mauriciovieira) [inline branding/logo/client/upload/resumable.js]: Since this is a backend error, my suggestion is to adopt some standard here. My suggestion is to be pretty verbose (as we are with comments all over the code):
`throw new Meteor.Error('branding/logo/client/upload/resumable.js: File creation failed!', error);`

Comment (brylie) [inline branding/logo/client/upload/resumable.js]: @mauriciovieira I will make that change. Will you add a secction about excetion handling and error messages to our condtibutor guidelines, and include an example similar to the one here?

File: api_docs/client/swaggerUI/swaggerUiContent/swaggerUiContent.js (hunk 3 above)
Comment (brylie) [inline api_docs/client/swaggerUI/swaggerUiContent/swaggerUiContent.js]: I would need to defer to @marla-singer here. I am just refactoring the code, but didn't write this original block. I am not opposed to improving code nearby where I work, but need to draw a boundary at a reasonable extent.

Comment (brylie) [inline api_docs/client/swaggerUI/swaggerUiContent/swaggerUiContent.js]: I added a descriptive comment about the purpose of the rules, and a TODO to remind us to fix.

Comment (marla-singer) [inline api_docs/client/swaggerUI/swaggerUiContent/swaggerUiContent.js]: > Shouldn't it be better to fix the rules?

Unfortunately, this block `SwaggerUIBundle({});` came from [3rd library](https://github.com/swagger-api/swagger-ui#swaggeruibundle) and we can't control it

Comment (marla-singer) [inline api_docs/client/swaggerUI/swaggerUiContent/swaggerUiContent.js]: > Shouldn't it be better to fix the rules?

@mauriciovieira Unfortunately, this block `SwaggerUIBundle({});` came from [3rd library](https://github.com/swagger-api/swagger-ui#swaggeruibundle) and we can't control it

File: branding/logo/client/upload/resumable.js (hunk 5 above)
Comment (mauriciovieira) [inline branding/logo/client/upload/resumable.js]: Yes.

**Comment by bajiat** [comment]
Is this PR also related to this error?

codegen error 2017-05-24

This is present in nightly, staging and production

**Comment by brylie** [comment]
@bajiat This PR improves the error handling when the Codegen is misconfigured, so it could improve your reported error. Lets go ahead and open your report as its own issue, so we can track and resolve. We can reference this PR from the new issue.

**Comment by brylie** [comment]
@mauriciovieira what is the status of this PR review? It has been marked as ready for review for seven days.

File: api_docs/client/code_generator/modal.html [hunk 6]
```diff
@@ -16,20 +16,16 @@ <h1 class="modal-title">
...
-            doc=getTemplateInstance
-            buttonContent=buttonText }}
-        {{ else }}
-          {{> spinner }}
-         {{/ if }}
-
-      {{# if statusRequest }}
-        {{> spinner }}
-      {{/ if }}
+        {{#autoForm id="downloadSDK" type="normal" schema=codeGeneratorSchema }}
```
Comment (marla-singer) [inline api_docs/client/code_generator/modal.html]: @brylie Space between `#` and `autoForm`

File: api_docs/client/code_generator/modal.html [hunk 7]
```diff
@@ -16,20 +16,16 @@ <h1 class="modal-title">
...
+          <fieldset>
+            {{> afQuickField name='selectLanguage'}}
```
Comment (marla-singer) [inline api_docs/client/code_generator/modal.html]: Space between `'` and `}}`

File: api_docs/client/code_generator/modal.html [hunk 8]
```diff
@@ -16,20 +16,16 @@ <h1 class="modal-title">
...
+            {{> afQuickField name='host' value=host type='hidden' }}
+            {{> afQuickField name='documentationFileURL' value=api.documentationUrl type='hidden' }}
+          </fieldset>
+          <button type="submit" class="btn btn-primary">
+            {{_ "sdkCodeGeneratorModal_buttonText_download" }}
+          </button>
+        {{/autoForm}}
```
Comment (marla-singer) [inline api_docs/client/code_generator/modal.html]: Spaces between `/` and `autoForm` before `}}`

File: api_docs/client/code_generator/schema.js [hunk 9]
```diff
@@ -0,0 +1,34 @@
...
+This file is covered by the EUPL license.
+You may obtain a copy of the licence at
+https://joinup.ec.europa.eu/community/eupl/og_page/european-union-public-licence-eupl-v11 */
+
+// Meteor contributed packages imports
+import { SimpleSchema } from 'meteor/aldeed:simple-schema';
+import { TAPi18n } from 'meteor/tap:i18n';
+
+// APInf specific imports
+import codeGeneratorLanguageOptions from './code_generator_language_options';
```
Comment (marla-singer) [inline api_docs/client/code_generator/schema.js]: Rename comment as `// APINF imports`

File: api_docs/client/code_generator/schema.js [hunk 10]
```diff
@@ -0,0 +1,34 @@
...
+
+const codeGeneratorSchema = new SimpleSchema({
+  selectLanguage: {
+    label: TAPi18n.__('sdkCodeGeneratorModal_labelText_selectLanguage'),
```
Comment (marla-singer) [inline api_docs/client/code_generator/schema.js]: Add property as `optional: false`

File: api_docs/client/code_generator/schema.js [hunk 11]
```diff
@@ -0,0 +1,34 @@
...
+      afFieldInput: {
+        firstOption: TAPi18n.__('sdkCodeGeneratorModal_firstOption_language'),
+      },
+      options () {
+        return codeGeneratorLanguageOptions;
+      },
+    },
+  },
+  host: {
+    type: String,
```
Comment (marla-singer) [inline api_docs/client/code_generator/schema.js]: Add property as `optional: false`

File: api_docs/client/code_generator/schema.js [hunk 12]
```diff
@@ -0,0 +1,34 @@
...
+  },
+  documentationFileURL: {
+    type: String,
```
Comment (marla-singer) [inline api_docs/client/code_generator/schema.js]: Add property as `optional: false`

**Comment by brylie** [comment]
The SDK form language select first option has been [internationalized](https://github.com/apinf/platform/blob/develop/core/lib/i18n/en.i18n.json#L1019), but not localized.

sdk form

**Comment by brylie** [comment]
@marla-singer I made the requested changes.

File: api_docs/client/code_generator/schema.js (hunk 10 above)
Comment (marla-singer) [inline api_docs/client/code_generator/schema.js]: @brylie You forgot about this field

**Comment by marla-singer** [comment]
Translation doesn't still work on local, on nightly.apinf.io does 
joxi_screenshot_1495625055002

**Comment by brylie** [comment]
@marla-singer fixed.

File: api_docs/client/code_generator/modal.js [hunk 13]
```diff
@@ -6,13 +6,40 @@ https://joinup.ec.europa.eu/community/eupl/og_page/european-union-public-licence
...
-import codeGeneratorSchema from './schema';
+import codeGeneratorLanguageOptions from './code_generator_language_options';
 
 Template.sdkCodeGeneratorModal.helpers({
   // Schema for SDK Code Generator form
   codeGeneratorSchema () {
     // Create simple schema for sdk modal
+    const codeGeneratorSchema = new SimpleSchema({
+      selectLanguage: {
+        label: TAPi18n.__('sdkCodeGeneratorModal_labelText_selectLanguage'),
```
Comment (marla-singer) [inline api_docs/client/code_generator/modal.js]: Add property as `optional: false,`

Comment (brylie) [inline api_docs/client/code_generator/modal.js]: Done.
